#!/usr/bin/env bash
# Regenerate native/Vendor/Excalidraw/web/ - the self-contained, offline
# Excalidraw bundle the Whiteboard destination loads.
#
# Run this by hand after changing native/Vendor/Excalidraw/src/*, or after
# bumping a pinned version in src/package.json. It is NOT part of `swift build`
# and never runs at app launch: the output is committed, exactly like every
# other vendored dependency in this repo (see native/Vendor/Excalidraw/README.md
# and the identical convention in native/Vendor/whisper.cpp/README.md for the
# generated Metal shader source).
#
# Needs node/npm and network access - the one and only time either is needed.
# The app itself never touches node or the network for this feature.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="Vendor/Excalidraw/src"
OUT="Vendor/Excalidraw/web"
WORK="$(mktemp -d /tmp/grandline-excalidraw-build.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

command -v npm >/dev/null || { echo "npm is required (build-time only)"; exit 1; }

echo "Installing pinned deps into $WORK …"
cp "$SRC/package.json" "$WORK/package.json"
(cd "$WORK" && npm install --silent --no-audit --no-fund)

EX="$WORK/node_modules/@excalidraw/excalidraw"
VERSION="$(node -p "require('$EX/package.json').version")"
echo "Bundling @excalidraw/excalidraw $VERSION …"

cp "$SRC/whiteboard.js" "$WORK/entry.js"

# One classic IIFE file, everything inlined - see src/index.html for why a
# module graph is deliberately avoided on a file:// origin. `--conditions
# =production` is what selects Excalidraw's own dist/prod tree over dist/dev
# (its package exports gate on that condition, and without it esbuild cannot
# resolve ./index.css at all).
(cd "$WORK" && ./node_modules/.bin/esbuild entry.js \
  --bundle \
  --format=iife \
  --minify \
  --target=safari16 \
  --conditions=production \
  '--define:process.env.NODE_ENV="production"' \
  --loader:.woff2=copy \
  '--asset-names=fonts/[name]' \
  --outfile=out/whiteboard.js \
  --log-level=warning)

rm -rf "$OUT"
mkdir -p "$OUT"
cp "$WORK/out/whiteboard.js" "$OUT/whiteboard.js"
cp "$WORK/out/whiteboard.css" "$OUT/whiteboard.css"
cp "$SRC/index.html" "$OUT/index.html"

# The woff2 subsets Excalidraw fetches lazily at runtime, resolved against
# `window.EXCALIDRAW_ASSET_PATH` (set to "./" by the entry file). Copied from
# the package's own dist/prod tree rather than re-derived.
#
# Xiaolai is deliberately excluded: it is 12MB of CJK handwriting subsets -
# 95% of the whole font payload - for glyph coverage this captain's boards do
# not use. Excalidraw falls back to a system face for anything it cannot find,
# so the cost of the exclusion is CJK text rendering in a non-handwritten font
# rather than anything breaking. Re-add the directory here if that ever matters.
mkdir -p "$OUT/fonts"
for dir in "$EX"/dist/prod/fonts/*/; do
  name="$(basename "$dir")"
  [ "$name" = "Xiaolai" ] && continue
  cp -R "$dir" "$OUT/fonts/$name"
done

cat > "$OUT/BUILD-INFO.txt" <<INFO
Generated by native/Scripts/build-excalidraw-web.sh - do not edit by hand.
@excalidraw/excalidraw $VERSION
react $(node -p "require('$WORK/node_modules/react/package.json').version")
react-dom $(node -p "require('$WORK/node_modules/react-dom/package.json').version")
esbuild $(cd "$WORK" && ./node_modules/.bin/esbuild --version)
Fonts copied from the package's dist/prod/fonts, excluding Xiaolai (CJK subsets).
INFO

echo ""
echo "✓ Wrote $OUT"
du -sh "$OUT" "$OUT/whiteboard.js" "$OUT/fonts"
