#!/usr/bin/env bash
# Regenerate native/Vendor/Excalidraw/web/ - the self-contained, offline
# Excalidraw bundle the Whiteboard destination loads.
#
# Run this by hand after changing native/Vendor/Excalidraw/src/*, or after
# bumping a pinned version in src/package.json. It is NOT part of `swift build`
# and never runs at app launch: the output is committed, exactly like every
# other vendored dependency in this repo (see native/Vendor/Excalidraw/README.md
# and the identical convention in native/Vendor/whisper.cpp/README.md for the
# generated Metal shader source).
#
# Needs node/npm and network access - the one and only time either is needed.
# The app itself never touches node or the network for this feature.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="Vendor/Excalidraw/src"
OUT="Vendor/Excalidraw/web"
WORK="$(mktemp -d /tmp/grandline-excalidraw-build.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

# P11: `--check` rebuilds into a scratch directory and diffs it against the
# committed bundle instead of replacing it, so drift between `src/` and `web/`
# fails loudly rather than waiting for somebody to remember to regenerate. It
# is only reproducible because the install is `npm ci` against a committed
# lockfile - see the note below.
#
# Deliberately not wired into CI's `generated` job, which has no node and would
# have to install Excalidraw, React and esbuild on every pull request for a
# bundle that changes a few times a year. The review's own suggestion is a
# scheduled job, and that is the captain's call; what this flag does is make
# the check one command rather than a manual rebuild-and-eyeball.
CHECK_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_ONLY=1 ;;
    *) echo "unknown argument: $arg (--check is the only one)" >&2; exit 2 ;;
  esac
done

command -v npm >/dev/null || { echo "npm is required (build-time only)"; exit 1; }

echo "Installing pinned deps into $WORK …"
# P11 (2026-09-25 review): "vendored Excalidraw and Monaco have no lockfile
# and no --check". `package.json` pins the direct versions and nothing pinned
# the transitive tree, so two runs of this script a month apart could produce
# two different committed bundles from the same inputs - which is also the
# reason CI's own `generated` job excludes these two ("a drift failure would as
# often mean npm resolved a different patch version today"). `npm ci` installs
# exactly the committed lockfile and fails rather than resolving anything, so
# the rebuild is reproducible and that objection is now about runner cost
# rather than about correctness.
#
# Regenerate the lockfile with `npm install --package-lock-only` in
# `Vendor/<name>/src/` after bumping a pinned version, and commit it in the
# same change as the rebuilt bundle.
cp "$SRC/package.json" "$WORK/package.json"
cp "$SRC/package-lock.json" "$WORK/package-lock.json"
(cd "$WORK" && npm ci --silent --no-audit --no-fund)

EX="$WORK/node_modules/@excalidraw/excalidraw"
VERSION="$(node -p "require('$EX/package.json').version")"
echo "Bundling @excalidraw/excalidraw $VERSION …"

cp "$SRC/whiteboard.js" "$WORK/entry.js"

# One classic IIFE file, everything inlined - see src/index.html for why a
# module graph is deliberately avoided on a file:// origin. `--conditions
# =production` is what selects Excalidraw's own dist/prod tree over dist/dev
# (its package exports gate on that condition, and without it esbuild cannot
# resolve ./index.css at all).
(cd "$WORK" && ./node_modules/.bin/esbuild entry.js \
  --bundle \
  --format=iife \
  --minify \
  --target=safari16 \
  --conditions=production \
  '--define:process.env.NODE_ENV="production"' \
  --loader:.woff2=copy \
  '--asset-names=fonts/[name]' \
  --outfile=out/whiteboard.js \
  --log-level=warning)

# Everything below writes to $DEST: the committed tree on a real run, a
# scratch copy under --check.
if [ "$CHECK_ONLY" -eq 1 ]; then DEST="$WORK/check-out"; else DEST="$OUT"; fi
rm -rf "$DEST"
mkdir -p "$DEST"
cp "$WORK/out/whiteboard.js" "$DEST/whiteboard.js"
cp "$WORK/out/whiteboard.css" "$DEST/whiteboard.css"
cp "$SRC/index.html" "$DEST/index.html"

# The woff2 subsets Excalidraw fetches lazily at runtime, resolved against
# `window.EXCALIDRAW_ASSET_PATH` (set to "./" by the entry file). Copied from
# the package's own dist/prod tree rather than re-derived.
#
# Xiaolai is deliberately excluded: it is 12MB of CJK handwriting subsets -
# 95% of the whole font payload - for glyph coverage this captain's boards do
# not use. Excalidraw falls back to a system face for anything it cannot find,
# so the cost of the exclusion is CJK text rendering in a non-handwritten font
# rather than anything breaking. Re-add the directory here if that ever matters.
mkdir -p "$DEST/fonts"
for dir in "$EX"/dist/prod/fonts/*/; do
  name="$(basename "$dir")"
  [ "$name" = "Xiaolai" ] && continue
  cp -R "$dir" "$DEST/fonts/$name"
done

cat > "$DEST/BUILD-INFO.txt" <<INFO
Generated by native/Scripts/build-excalidraw-web.sh - do not edit by hand.
@excalidraw/excalidraw $VERSION
react $(node -p "require('$WORK/node_modules/react/package.json').version")
react-dom $(node -p "require('$WORK/node_modules/react-dom/package.json').version")
esbuild $(cd "$WORK" && ./node_modules/.bin/esbuild --version)
Fonts copied from the package's dist/prod/fonts, excluding Xiaolai (CJK subsets).
INFO

if [ "$CHECK_ONLY" -eq 1 ]; then
  if diff -r "$OUT" "$DEST" >/dev/null 2>&1; then
    echo ""
    echo "✓ $OUT matches a rebuild from $SRC"
    exit 0
  fi
  echo ""
  echo "✗ $OUT does NOT match a rebuild from $SRC:" >&2
  # `-q` rather than a real diff: these are minified single-line bundles, so a
  # character-level diff is megabytes of noise. Names of the files that differ
  # is the useful answer; the rebuild is sitting in $DEST to compare by hand.
  diff -rq "$OUT" "$DEST" >&2
  echo "" >&2
  echo "  Run this script without --check and commit the result." >&2
  exit 1
fi

echo ""
echo "✓ Wrote $OUT"
du -sh "$OUT" "$OUT/whiteboard.js" "$OUT/fonts"
