#!/usr/bin/env bash
# Regenerate native/Vendor/Monaco/web/ - the self-contained, offline Monaco
# Editor bundle the Code Preview destination loads.
#
# Run this by hand after changing native/Vendor/Monaco/src/*, or after bumping
# a pinned version in src/package.json. It is NOT part of `swift build` and
# never runs at app launch: the output is committed, exactly like every other
# vendored dependency in this repo (see native/Vendor/Monaco/README.md, and the
# identical convention in native/Scripts/build-excalidraw-web.sh, which this
# script is deliberately modelled on line for line).
#
# Needs node/npm and network access - the one and only time either is needed.
# The app itself never touches node or the network for this feature.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="Vendor/Monaco/src"
OUT="Vendor/Monaco/web"
WORK="$(mktemp -d /tmp/grandline-monaco-build.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

# P11: `--check` rebuilds into a scratch directory and diffs it against the
# committed bundle instead of replacing it, so drift between `src/` and `web/`
# fails loudly rather than waiting for somebody to remember to regenerate. It
# is only reproducible because the install is `npm ci` against a committed
# lockfile - see the note below.
#
# Deliberately not wired into CI's `generated` job, which has no node and would
# have to install Excalidraw, React and esbuild on every pull request for a
# bundle that changes a few times a year. The review's own suggestion is a
# scheduled job, and that is the captain's call; what this flag does is make
# the check one command rather than a manual rebuild-and-eyeball.
CHECK_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_ONLY=1 ;;
    *) echo "unknown argument: $arg (--check is the only one)" >&2; exit 2 ;;
  esac
done

command -v npm >/dev/null || { echo "npm is required (build-time only)"; exit 1; }

echo "Installing pinned deps into $WORK …"
# P11 (2026-09-25 review): "vendored Excalidraw and Monaco have no lockfile
# and no --check". `package.json` pins the direct versions and nothing pinned
# the transitive tree, so two runs of this script a month apart could produce
# two different committed bundles from the same inputs - which is also the
# reason CI's own `generated` job excludes these two ("a drift failure would as
# often mean npm resolved a different patch version today"). `npm ci` installs
# exactly the committed lockfile and fails rather than resolving anything, so
# the rebuild is reproducible and that objection is now about runner cost
# rather than about correctness.
#
# Regenerate the lockfile with `npm install --package-lock-only` in
# `Vendor/<name>/src/` after bumping a pinned version, and commit it in the
# same change as the rebuilt bundle.
cp "$SRC/package.json" "$WORK/package.json"
cp "$SRC/package-lock.json" "$WORK/package-lock.json"
(cd "$WORK" && npm ci --silent --no-audit --no-fund)

VERSION="$(node -p "require('$WORK/node_modules/monaco-editor/package.json').version")"
echo "Bundling monaco-editor $VERSION …"

cp "$SRC/code-preview.js" "$WORK/entry.js"
cp "$SRC/editor.worker.entry.js" "$WORK/worker-entry.js"

# Two passes, and the order matters. Monaco's editor worker is bundled first,
# then handed to the main build as *text* so it ends up inlined in the one
# committed script - see Vendor/Monaco/src/code-preview.js's "The worker"
# section for why a sibling worker file is not an option on a file:// origin.
(cd "$WORK" && ./node_modules/.bin/esbuild worker-entry.js \
  --bundle \
  --format=iife \
  --minify \
  --target=safari16 \
  '--define:process.env.NODE_ENV="production"' \
  --outfile=editor.worker.bundle.txt \
  --log-level=warning)

# One classic IIFE file, everything inlined - see src/index.html for why a
# module graph is deliberately avoided on a file:// origin.
#
# `--loader:.ttf=dataurl` is what makes the codicon glyph font part of the CSS
# rather than a file to fetch, which is what lets the CSP get away with
# `font-src 'self' data:` and no font directory at all (unlike Excalidraw,
# whose woff2 subsets are genuinely lazy-loaded at runtime).
(cd "$WORK" && ./node_modules/.bin/esbuild entry.js \
  --bundle \
  --format=iife \
  --minify \
  --target=safari16 \
  '--define:process.env.NODE_ENV="production"' \
  --loader:.ttf=dataurl \
  --loader:.txt=text \
  --outfile=out/code-preview.js \
  --log-level=warning)

# Everything below writes to $DEST: the committed tree on a real run, a
# scratch copy under --check.
if [ "$CHECK_ONLY" -eq 1 ]; then DEST="$WORK/check-out"; else DEST="$OUT"; fi
rm -rf "$DEST"
mkdir -p "$DEST"
cp "$WORK/out/code-preview.js" "$DEST/code-preview.js"
cp "$WORK/out/code-preview.css" "$DEST/code-preview.css"
cp "$SRC/index.html" "$DEST/index.html"

cat > "$DEST/BUILD-INFO.txt" <<INFO
Generated by native/Scripts/build-monaco-web.sh - do not edit by hand.
monaco-editor $VERSION
esbuild $(cd "$WORK" && ./node_modules/.bin/esbuild --version)
Imported: editor.all.js (the editor's own contributions) + editor.api.js.
Deliberately NOT imported: vs/language/{typescript,json,css,html} - those are
the IntelliSense/validation services, which this panel does not carry. JSON is
covered by a small Monarch tokenizer defined in src/code-preview.js instead.
Languages: swift yaml python go rust shell javascript typescript dockerfile
sql hcl markdown xml ini (+ json, hand-written) - a hand-picked set, not
monaco's full ~90.
The codicon glyph font is inlined into the CSS as a data: URI, and the editor
worker is inlined into the JS as source text: web/ has no other files and the
page fetches nothing.
INFO

if [ "$CHECK_ONLY" -eq 1 ]; then
  if diff -r "$OUT" "$DEST" >/dev/null 2>&1; then
    echo ""
    echo "✓ $OUT matches a rebuild from $SRC"
    exit 0
  fi
  echo ""
  echo "✗ $OUT does NOT match a rebuild from $SRC:" >&2
  # `-q` rather than a real diff: these are minified single-line bundles, so a
  # character-level diff is megabytes of noise. Names of the files that differ
  # is the useful answer; the rebuild is sitting in $DEST to compare by hand.
  diff -rq "$OUT" "$DEST" >&2
  echo "" >&2
  echo "  Run this script without --check and commit the result." >&2
  exit 1
fi

echo ""
echo "✓ Wrote $OUT"
du -sh "$OUT" "$OUT/code-preview.js" "$OUT/code-preview.css"
