#!/usr/bin/env bash
# Regenerate native/Vendor/Monaco/web/ - the self-contained, offline Monaco
# Editor bundle the Code Preview destination loads.
#
# Run this by hand after changing native/Vendor/Monaco/src/*, or after bumping
# a pinned version in src/package.json. It is NOT part of `swift build` and
# never runs at app launch: the output is committed, exactly like every other
# vendored dependency in this repo (see native/Vendor/Monaco/README.md, and the
# identical convention in native/Scripts/build-excalidraw-web.sh, which this
# script is deliberately modelled on line for line).
#
# Needs node/npm and network access - the one and only time either is needed.
# The app itself never touches node or the network for this feature.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="Vendor/Monaco/src"
OUT="Vendor/Monaco/web"
WORK="$(mktemp -d /tmp/grandline-monaco-build.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

command -v npm >/dev/null || { echo "npm is required (build-time only)"; exit 1; }

echo "Installing pinned deps into $WORK …"
cp "$SRC/package.json" "$WORK/package.json"
(cd "$WORK" && npm install --silent --no-audit --no-fund)

VERSION="$(node -p "require('$WORK/node_modules/monaco-editor/package.json').version")"
echo "Bundling monaco-editor $VERSION …"

cp "$SRC/code-preview.js" "$WORK/entry.js"
cp "$SRC/editor.worker.entry.js" "$WORK/worker-entry.js"

# Two passes, and the order matters. Monaco's editor worker is bundled first,
# then handed to the main build as *text* so it ends up inlined in the one
# committed script - see Vendor/Monaco/src/code-preview.js's "The worker"
# section for why a sibling worker file is not an option on a file:// origin.
(cd "$WORK" && ./node_modules/.bin/esbuild worker-entry.js \
  --bundle \
  --format=iife \
  --minify \
  --target=safari16 \
  '--define:process.env.NODE_ENV="production"' \
  --outfile=editor.worker.bundle.txt \
  --log-level=warning)

# One classic IIFE file, everything inlined - see src/index.html for why a
# module graph is deliberately avoided on a file:// origin.
#
# `--loader:.ttf=dataurl` is what makes the codicon glyph font part of the CSS
# rather than a file to fetch, which is what lets the CSP get away with
# `font-src 'self' data:` and no font directory at all (unlike Excalidraw,
# whose woff2 subsets are genuinely lazy-loaded at runtime).
(cd "$WORK" && ./node_modules/.bin/esbuild entry.js \
  --bundle \
  --format=iife \
  --minify \
  --target=safari16 \
  '--define:process.env.NODE_ENV="production"' \
  --loader:.ttf=dataurl \
  --loader:.txt=text \
  --outfile=out/code-preview.js \
  --log-level=warning)

rm -rf "$OUT"
mkdir -p "$OUT"
cp "$WORK/out/code-preview.js" "$OUT/code-preview.js"
cp "$WORK/out/code-preview.css" "$OUT/code-preview.css"
cp "$SRC/index.html" "$OUT/index.html"

cat > "$OUT/BUILD-INFO.txt" <<INFO
Generated by native/Scripts/build-monaco-web.sh - do not edit by hand.
monaco-editor $VERSION
esbuild $(cd "$WORK" && ./node_modules/.bin/esbuild --version)
Imported: editor.all.js (the editor's own contributions) + editor.api.js.
Deliberately NOT imported: vs/language/{typescript,json,css,html} - those are
the IntelliSense/validation services, which this panel does not carry. JSON is
covered by a small Monarch tokenizer defined in src/code-preview.js instead.
Languages: swift yaml python go rust shell javascript typescript dockerfile
sql hcl markdown xml ini (+ json, hand-written) - a hand-picked set, not
monaco's full ~90.
The codicon glyph font is inlined into the CSS as a data: URI, and the editor
worker is inlined into the JS as source text: web/ has no other files and the
page fetches nothing.
INFO

echo ""
echo "✓ Wrote $OUT"
du -sh "$OUT" "$OUT/code-preview.js" "$OUT/code-preview.css"
