// Grand Line - native macOS app.
//
// Follow-up to fm/grandline-dictation-whisper-engine (CPU-only baseline
// vendoring): enables the vendored whisper.cpp's Metal backend at runtime.
// See Vendor/whisper.cpp/README.md's "Metal acceleration" section for the
// full writeup - this file is the one piece of Swift-side plumbing that
// makes it work without CMake/Xcode.
//
// whisper.cpp's Metal backend (`ggml_metal_library_init`, vendored at
// `Vendor/whisper.cpp/Sources/CWhisper/ggml-src/ggml-metal/`) looks for its
// shader source in this order: an embedded-at-compile-time blob (not used
// here - that needs a CMake-generated assembly file), a `default.metallib`/
// `ggml-metal.metal` inside a resource bundle (not reliable here either -
// `build_native_app.sh` never copies any SwiftPM-generated `*.bundle`
// directory into the assembled .app), then the `GGML_METAL_PATH_RESOURCES`
// environment variable pointed at a directory containing a real
// `ggml-metal.metal` file - a real, documented upstream mechanism meant for
// exactly this "no bundle" situation. This file writes the embedded,
// pre-merged shader source (`WhisperMetalShaderSource.swift`, generated by
// `native/Scripts/build-whisper-metal-shader.py`) to a real file under the
// same directory `WhisperModelManager` already resolves, then points
// `GGML_METAL_PATH_RESOURCES` there before the first whisper.cpp Metal
// backend init happens.
//
// A first attempt at this assumed `whisper_backend_init_gpu` failing
// gracefully (returning `nullptr`, logging, and letting `whisper_backend_init`
// fall back to CPU-only) would be enough on its own, matching how a *missing
// GPU device* is handled. Live-verified forcing a real Metal-library-load
// failure (`FM_WHISPER_METAL_RESOURCES_OVERRIDE` pointed at a directory with
// no shader file) instead found a real crash one layer up: `whisper_init`'s
// `make_buft_list` (`whisper-src/whisper.cpp`) adds the GPU device's buffer
// type to the model's buffer-type list whenever `params.use_gpu` is `true`,
// unconditionally - it does not check whether `whisper_backend_init_gpu`
// actually produced a working backend for that device. When the Metal
// library fails to load, `whisper_backend_init_gpu` correctly returns `nil`
// and no Metal backend gets registered - but the model's tensors are still
// pre-allocated into the (now backend-less) MTL0 buffer type, and
// `ggml_backend_sched_split_graph` hits an unrecoverable `ggml_abort` the
// moment it tries to schedule an op against a buffer no live backend claims
// - confirmed live, reproduced with the override above, real crash log
// included in this PR's description. This cannot be caught from Swift (a
// ggml abort calls the C `abort()`, not a throwable Swift error), so the
// only safe fix is to never let `whisper_init` see `use_gpu = true` unless
// Metal is already known to actually work.
//
// `metalCanCompileShader()` below is that pre-flight: it performs the exact
// same compile whisper.cpp's own `ggml_metal_library_init` would attempt -
// same device, same resolution order (an `FM_WHISPER_METAL_RESOURCES_OVERRIDE`
// test override first, else the real embedded shader text) - entirely from
// Swift, before `WhisperCppEngine.init?` ever calls into whisper.cpp. If it
// succeeds, whisper.cpp's own internal compile of the identical source is
// guaranteed to succeed too (same device, same text), so the crash path
// above can no longer be reached; if it fails, `use_gpu` stays `false` and
// whisper.cpp only ever sees its already-safe CPU-only path. The result is
// cached for the process's lifetime - Metal availability does not change
// mid-run, and macOS's own system-wide compiled-shader cache (confirmed
// live: a cold compile of this shader took ~9s, a second compile of the
// identical source in a fresh process took ~0.01s) means this adds no real
// repeat cost even across separate recordings.
import Foundation
import Metal

enum WhisperMetalRuntime {
    private static var prepared = false
    private static var cachedMetalAvailable: Bool?

    /// Must be called before the first `WhisperCppEngine.init?` in a process
    /// (idempotent - a second call is a no-op). Not thread-safe by itself;
    /// `WhisperCppEngine.init?` only ever runs on `DictationEngine`'s single
    /// background queue (see that type's own doc comment on `whisper_full`
    /// not being reentrant), so there is no concurrent-call risk in
    /// practice.
    static func prepareIfNeeded() {
        guard !prepared else { return }
        prepared = true

        // Test-only escape hatch (see WhisperEngineSelfTest's Metal-
        // fallback case): point straight at a caller-supplied directory
        // instead of writing our own shader file there, so a test can force
        // Metal library init to fail (no file, or a deliberately-broken one)
        // and confirm the CPU/Apple-Speech fallback chain still works with
        // no crash.
        if let override = ProcessInfo.processInfo.environment["FM_WHISPER_METAL_RESOURCES_OVERRIDE"], !override.isEmpty {
            setenv("GGML_METAL_PATH_RESOURCES", override, 1)
            return
        }

        let dir = WhisperModelManager.directoryURL()
        do {
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            let shaderURL = dir.appendingPathComponent("ggml-metal.metal")
            // PF8: built on demand and released as soon as it is written.
            try WhisperMetalShaderSource.make().write(to: shaderURL, atomically: true, encoding: .utf8)
            setenv("GGML_METAL_PATH_RESOURCES", dir.path, 1)
        } catch {
            // Can't write the shader source anywhere real (disk full,
            // permissions, ...) - leave GGML_METAL_PATH_RESOURCES unset, so
            // the pre-flight check below (which also probes this same path)
            // correctly reports Metal as unavailable rather than attempting
            // a load that would fail.
        }
    }

    /// Returns whether whisper.cpp's Metal backend can actually be used on
    /// this machine right now - call after `prepareIfNeeded()`, before
    /// deciding `whisper_context_params.use_gpu`. See this file's header
    /// comment for why this pre-flight exists (a real crash found one layer
    /// inside whisper.cpp itself when Metal library load fails with
    /// `use_gpu = true`, not just a graceful fallback). Cached after the
    /// first call - Metal availability cannot change mid-process.
    static func metalCanCompileShader() -> Bool {
        if let cached = cachedMetalAvailable { return cached }
        let result = computeMetalCanCompileShader()
        cachedMetalAvailable = result
        return result
    }

    private static func computeMetalCanCompileShader() -> Bool {
        guard let device = MTLCreateSystemDefaultDevice() else { return false }

        let source: String
        // Mirrors ggml_metal_library_init's own resolution order exactly
        // (GGML_METAL_PATH_RESOURCES first) so the test-only override above
        // is honored here too - a deliberately-missing/broken override file
        // must make this pre-flight fail the same way a real Metal problem
        // would, or the override couldn't prove the fallback path works.
        if let resourcesDir = ProcessInfo.processInfo.environment["GGML_METAL_PATH_RESOURCES"], !resourcesDir.isEmpty {
            let path = (resourcesDir as NSString).appendingPathComponent("ggml-metal.metal")
            guard let fileSource = try? String(contentsOfFile: path, encoding: .utf8) else { return false }
            source = fileSource
        } else {
            source = WhisperMetalShaderSource.make()
        }

        do {
            _ = try device.makeLibrary(source: source, options: MTLCompileOptions())
            return true
        } catch {
            return false
        }
    }
}
