// Manjesh Grand Line - native macOS app.
//
// GENERATED by native/Scripts/build-whiteboard-icons.py - do not edit by hand.
// Run that script with --check to confirm this file matches its sources.
//
// One `data:` URL per Whiteboard component: a white chip carrying the
// component's glyph in its role hue. See the generator's own docstring for
// where the glyphs come from, which icon sets were rejected and why, and why
// the chip is drawn this way rather than as a solid AWS-style tile.
//
// Glyphs: Material Symbols, Apache License 2.0 (Google). The licence text
// ships at native/Scripts/assets/whiteboard-icons/LICENSE-material-symbols.txt.

enum WhiteboardIcons {

    /// Keyed by `DiagramComponent.keyword`, which is the stable identifier a
    /// saved board and the DSL both already use.
    static let dataURLs: [String: String] = [
        // server -> Material Symbols "dns"
        "server":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMxOTcxYzIiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTMwMC03MjBxLT" +
            "I1IDAtNDIuNSAxNy41VDI0MC02NjBxMCAyNSAxNy41IDQyLjVUMzAwLTYwMHEyNSAwIDQyLjUtMTcuNVQzNjAtNjYwcTAtMjUtMT" +
            "cuNS00Mi41VDMwMC03MjBabTAgNDAwcS0yNSAwLTQyLjUgMTcuNVQyNDAtMjYwcTAgMjUgMTcuNSA0Mi41VDMwMC0yMDBxMjUgMC" +
            "A0Mi41LTE3LjVUMzYwLTI2MHEwLTI1LTE3LjUtNDIuNVQzMDAtMzIwWk0xNjAtODQwaDY0MHExNyAwIDI4LjUgMTEuNVQ4NDAtOD" +
            "AwdjI4MHEwIDE3LTExLjUgMjguNVQ4MDAtNDgwSDE2MHEtMTcgMC0yOC41LTExLjVUMTIwLTUyMHYtMjgwcTAtMTcgMTEuNS0yOC" +
            "41VDE2MC04NDBabTAgNDAwaDY0MHExNyAwIDI4LjUgMTEuNVQ4NDAtNDAwdjI4MHEwIDE3LTExLjUgMjguNVQ4MDAtODBIMTYwcS" +
            "0xNyAwLTI4LjUtMTEuNVQxMjAtMTIwdi0yODBxMC0xNyAxMS41LTI4LjVUMTYwLTQ0MFoiIGZpbGw9IiMxOTcxYzIiLz48L3N2Zz" +
            "48L3N2Zz4=",
        // k8s -> Material Symbols "deployed_code"
        "k8s":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwYzg1OTkiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ0MC05MSAxNj" +
            "AtMjUycS0xOS0xMS0yOS41LTI5VDEyMC0zMjF2LTMxOHEwLTIyIDEwLjUtNDB0MjkuNS0yOWwyODAtMTYxcTE5LTExIDQwLTExdD" +
            "QwIDExbDI4MCAxNjFxMTkgMTEgMjkuNSAyOXQxMC41IDQwdjMxOHEwIDIyLTEwLjUgNDBUODAwLTI1Mkw1MjAtOTFxLTE5IDExLT" +
            "QwIDExdC00MC0xMVptMC0zNjZ2Mjc0bDQwIDIzIDQwLTIzdi0yNzRsMjQwLTEzOXYtNDJsLTQzLTI1LTIzNyAxMzctMjM3LTEzNy" +
            "00MyAyNXY0MmwyNDAgMTM5WiIgZmlsbD0iIzBjODU5OSIvPjwvc3ZnPjwvc3ZnPg==",
        // db -> Material Symbols "database"
        "db":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMyZjllNDQiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC01MjBxMT" +
            "UwIDAgMjU1LTQ3dDEwNS0xMTNxMC02Ni0xMDUtMTEzdC0yNTUtNDdxLTE1MCAwLTI1NSA0N1QxMjAtNjgwcTAgNjYgMTA1IDExM3" +
            "QyNTUgNDdabTAgMTAwcTQxIDAgMTAyLjUtOC41VDcwMS00NTZxNTctMTkgOTgtNDkuNXQ0MS03NC41djEwMHEwIDQ0LTQxIDc0Lj" +
            "VUNzAxLTM1NnEtNTcgMTktMTE4LjUgMjcuNVQ0ODAtMzIwcS00MSAwLTEwMi41LTguNVQyNTktMzU2cS01Ny0xOS05OC00OS41VD" +
            "EyMC00ODB2LTEwMHEwIDQ0IDQxIDc0LjV0OTggNDkuNXE1NyAxOSAxMTguNSAyNy41VDQ4MC00MjBabTAgMjAwcTQxIDAgMTAyLj" +
            "UtOC41VDcwMS0yNTZxNTctMTkgOTgtNDkuNXQ0MS03NC41djEwMHEwIDQ0LTQxIDc0LjVUNzAxLTE1NnEtNTcgMTktMTE4LjUgMj" +
            "cuNVQ0ODAtMTIwcS00MSAwLTEwMi41LTguNVQyNTktMTU2cS01Ny0xOS05OC00OS41VDEyMC0yODB2LTEwMHEwIDQ0IDQxIDc0Lj" +
            "V0OTggNDkuNXE1NyAxOSAxMTguNSAyNy41VDQ4MC0yMjBaIiBmaWxsPSIjMmY5ZTQ0Ii8+PC9zdmc+PC9zdmc+",
        // queue -> Material Symbols "list_alt"
        "queue":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNmMDhjMDAiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTMyMC0yODBxMT" +
            "cgMCAyOC41LTExLjVUMzYwLTMyMHEwLTE3LTExLjUtMjguNVQzMjAtMzYwcS0xNyAwLTI4LjUgMTEuNVQyODAtMzIwcTAgMTcgMT" +
            "EuNSAyOC41VDMyMC0yODBabTAtMTYwcTE3IDAgMjguNS0xMS41VDM2MC00ODBxMC0xNy0xMS41LTI4LjVUMzIwLTUyMHEtMTcgMC" +
            "0yOC41IDExLjVUMjgwLTQ4MHEwIDE3IDExLjUgMjguNVQzMjAtNDQwWm0wLTE2MHExNyAwIDI4LjUtMTEuNVQzNjAtNjQwcTAtMT" +
            "ctMTEuNS0yOC41VDMyMC02ODBxLTE3IDAtMjguNSAxMS41VDI4MC02NDBxMCAxNyAxMS41IDI4LjVUMzIwLTYwMFptMTIwIDMyMG" +
            "gyNDB2LTgwSDQ0MHY4MFptMC0xNjBoMjQwdi04MEg0NDB2ODBabTAtMTYwaDI0MHYtODBINDQwdjgwWk0yMDAtMTIwcS0zMyAwLT" +
            "U2LjUtMjMuNVQxMjAtMjAwdi01NjBxMC0zMyAyMy41LTU2LjVUMjAwLTg0MGg1NjBxMzMgMCA1Ni41IDIzLjVUODQwLTc2MHY1Nj" +
            "BxMCAzMy0yMy41IDU2LjVUNzYwLTEyMEgyMDBaIiBmaWxsPSIjZjA4YzAwIi8+PC9zdmc+PC9zdmc+",
        // lb -> Material Symbols "device_hub"
        "lb":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiM5YzM2YjUiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTEyMC0xMjB2LT" +
            "IwMGgxNjBsMTYwLTE2MHYtMTI4cS0zNi0xMy01OC00My41VDM2MC03MjBxMC01MCAzNS04NXQ4NS0zNXE1MCAwIDg1IDM1dDM1ID" +
            "g1cTAgMzgtMjIgNjguNVQ1MjAtNjA4djEyOGwxNjAgMTYwaDE2MHYyMDBINjQwdi0xMjJMNDgwLTQwMiAzMjAtMjQydjEyMkgxMj" +
            "BaIiBmaWxsPSIjOWMzNmI1Ii8+PC9zdmc+PC9zdmc+",
        // secrets -> Material Symbols "lock"
        "secrets":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNlMDMxMzEiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTI0MC04MHEtMz" +
            "MgMC01Ni41LTIzLjVUMTYwLTE2MHYtNDAwcTAtMzMgMjMuNS01Ni41VDI0MC02NDBoNDB2LTgwcTAtODMgNTguNS0xNDEuNVQ0OD" +
            "AtOTIwcTgzIDAgMTQxLjUgNTguNVQ2ODAtNzIwdjgwaDQwcTMzIDAgNTYuNSAyMy41VDgwMC01NjB2NDAwcTAgMzMtMjMuNSA1Ni" +
            "41VDcyMC04MEgyNDBabTI0MC0yMDBxMzMgMCA1Ni41LTIzLjVUNTYwLTM2MHEwLTMzLTIzLjUtNTYuNVQ0ODAtNDQwcS0zMyAwLT" +
            "U2LjUgMjMuNVQ0MDAtMzYwcTAgMzMgMjMuNSA1Ni41VDQ4MC0yODBaTTM2MC02NDBoMjQwdi04MHEwLTUwLTM1LTg1dC04NS0zNX" +
            "EtNTAgMC04NSAzNXQtMzUgODV2ODBaIiBmaWxsPSIjZTAzMTMxIi8+PC9zdmc+PC9zdmc+",
        // actor -> Material Symbols "person"
        "actor":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMxZTFlMWUiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC00ODBxLT" +
            "Y2IDAtMTEzLTQ3dC00Ny0xMTNxMC02NiA0Ny0xMTN0MTEzLTQ3cTY2IDAgMTEzIDQ3dDQ3IDExM3EwIDY2LTQ3IDExM3QtMTEzID" +
            "Q3Wk0xNjAtMTYwdi0xMTJxMC0zNCAxNy41LTYyLjVUMjI0LTM3OHE2Mi0zMSAxMjYtNDYuNVQ0ODAtNDQwcTY2IDAgMTMwIDE1Lj" +
            "VUNzM2LTM3OHEyOSAxNSA0Ni41IDQzLjVUODAwLTI3MnYxMTJIMTYwWiIgZmlsbD0iIzFlMWUxZSIvPjwvc3ZnPjwvc3ZnPg==",
        // ec2 -> Material Symbols "computer"
        "ec2":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMxOTcxYzIiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTE2MC0yNDBxLT" +
            "MzIDAtNTYuNS0yMy41VDgwLTMyMHYtNDQwcTAtMzMgMjMuNS01Ni41VDE2MC04NDBoNjQwcTMzIDAgNTYuNSAyMy41VDg4MC03Nj" +
            "B2NDQwcTAgMzMtMjMuNSA1Ni41VDgwMC0yNDBIMTYwWk00MC0xMjB2LTgwaDg4MHY4MEg0MFoiIGZpbGw9IiMxOTcxYzIiLz48L3" +
            "N2Zz48L3N2Zz4=",
        // lambda -> Material Symbols "bolt"
        "lambda":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMxOTcxYzIiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0ibTMyMC04MCA0MC" +
            "0yODBIMTYwbDM2MC01MjBoODBsLTQwIDMyMGgyNDBMNDAwLTgwaC04MFoiIGZpbGw9IiMxOTcxYzIiLz48L3N2Zz48L3N2Zz4=",
        // ecs -> Material Symbols "grid_view"
        "ecs":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwYzg1OTkiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTEyMC01MjB2LT" +
            "MyMGgzMjB2MzIwSDEyMFptMCA0MDB2LTMyMGgzMjB2MzIwSDEyMFptNDAwLTQwMHYtMzIwaDMyMHYzMjBINTIwWm0wIDQwMHYtMz" +
            "IwaDMyMHYzMjBINTIwWiIgZmlsbD0iIzBjODU5OSIvPjwvc3ZnPjwvc3ZnPg==",
        // eks -> Material Symbols "hub"
        "eks":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwYzg1OTkiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTI0MC00MHEtNT" +
            "AgMC04NS0zNXQtMzUtODVxMC01MCAzNS04NXQ4NS0zNXExNCAwIDI2IDN0MjMgOGw1Ny03MXEtMjgtMzEtMzktNzB0LTUtNzhsLT" +
            "gxLTI3cS0xNyAyNS00MyA0MHQtNTggMTVxLTUwIDAtODUtMzVUMC01ODBxMC01MCAzNS04NXQ4NS0zNXE1MCAwIDg1IDM1dDM1ID" +
            "g1djhsODEgMjhxMjAtMzYgNTMuNS02MXQ3NS41LTMydi04N3EtMzktMTEtNjQuNS00Mi41VDM2MC04NDBxMC01MCAzNS04NXQ4NS" +
            "0zNXE1MCAwIDg1IDM1dDM1IDg1cTAgNDItMjYgNzMuNVQ1MTAtNzI0djg3cTQyIDcgNzUuNSAzMnQ1My41IDYxbDgxLTI4di04cT" +
            "AtNTAgMzUtODV0ODUtMzVxNTAgMCA4NSAzNXQzNSA4NXEwIDUwLTM1IDg1dC04NSAzNXEtMzIgMC01OC41LTE1VDczOS01MTVsLT" +
            "gxIDI3cTYgMzktNSA3Ny41VDYxNC0zNDBsNTcgNzBxMTEtNSAyMy03LjV0MjYtMi41cTUwIDAgODUgMzV0MzUgODVxMCA1MC0zNS" +
            "A4NXQtODUgMzVxLTUwIDAtODUtMzV0LTM1LTg1cTAtMjAgNi41LTM4LjVUNjI0LTIzMmwtNTctNzFxLTQxIDIzLTg3LjUgMjNUMz" +
            "kyLTMwM2wtNTYgNzFxMTEgMTUgMTcuNSAzMy41VDM2MC0xNjBxMCA1MC0zNSA4NXQtODUgMzVaIiBmaWxsPSIjMGM4NTk5Ii8+PC" +
            "9zdmc+PC9zdmc+",
        // alb -> Material Symbols "alt_route"
        "alb":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiM5YzM2YjUiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ0MC04MHYtMj" +
            "AwcTAtNTYtMTctODN0LTQ1LTUzbDU3LTU3cTEyIDExIDIzIDIzLjV0MjIgMjYuNXExNC0xOSAyOC41LTMzLjVUNTM4LTQ4NXEzOC" +
            "0zNSA2OS04MXQzMy0xNjFsLTYzIDYzLTU3LTU2IDE2MC0xNjAgMTYwIDE2MC01NiA1Ni02NC02M3EtMiAxNDMtNDQgMjAzLjVUNT" +
            "kyLTQyNXEtMzIgMjktNTIgNTYuNVQ1MjAtMjgwdjIwMGgtODBaTTI0OC02MzNxLTQtMjAtNS41LTQ0dC0yLjUtNTBsLTY0IDYzLT" +
            "U2LTU2IDE2MC0xNjAgMTYwIDE2MC01NyA1Ni02My02MnEwIDIxIDIgMzkuNXQ0IDM0LjVsLTc4IDE5Wm04NiAxNzZxLTIwLTIxLT" +
            "M4LjUtNDlUMjYzLTU3NWw3Ny0xOXExMCAyNyAyMyA0NnQyOCAzNGwtNTcgNTdaIiBmaWxsPSIjOWMzNmI1Ii8+PC9zdmc+PC9zdm" +
            "c+",
        // apigw -> Material Symbols "login"
        "apigw":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiM5YzM2YjUiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC0xMjB2LT" +
            "gwaDI4MHYtNTYwSDQ4MHYtODBoMjgwcTMzIDAgNTYuNSAyMy41VDg0MC03NjB2NTYwcTAgMzMtMjMuNSA1Ni41VDc2MC0xMjBIND" +
            "gwWm0tODAtMTYwLTU1LTU4IDEwMi0xMDJIMTIwdi04MGgzMjdMMzQ1LTYyMmw1NS01OCAyMDAgMjAwLTIwMCAyMDBaIiBmaWxsPS" +
            "IjOWMzNmI1Ii8+PC9zdmc+PC9zdmc+",
        // cloudfront -> Material Symbols "public"
        "cloudfront":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiM5YzM2YjUiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC04MHEtOD" +
            "MgMC0xNTYtMzEuNVQxOTctMTk3cS01NC01NC04NS41LTEyN1Q4MC00ODBxMC04MyAzMS41LTE1NlQxOTctNzYzcTU0LTU0IDEyNy" +
            "04NS41VDQ4MC04ODBxODMgMCAxNTYgMzEuNVQ3NjMtNzYzcTU0IDU0IDg1LjUgMTI3VDg4MC00ODBxMCA4My0zMS41IDE1NlQ3Nj" +
            "MtMTk3cS01NCA1NC0xMjcgODUuNVQ0ODAtODBabS00MC04MnYtNzhxLTMzIDAtNTYuNS0yMy41VDM2MC0zMjB2LTQwTDE2OC01NT" +
            "JxLTMgMTgtNS41IDM2dC0yLjUgMzZxMCAxMjEgNzkuNSAyMTJUNDQwLTE2MlptMjc2LTEwMnEyMC0yMiAzNi00Ny41dDI2LjUtNT" +
            "NxMTAuNS0yNy41IDE2LTU2LjV0NS41LTU5cTAtOTgtNTQuNS0xNzlUNjAwLTc3NnYxNnEwIDMzLTIzLjUgNTYuNVQ1MjAtNjgwaC" +
            "04MHY4MHEwIDE3LTExLjUgMjguNVQ0MDAtNTYwaC04MHY4MGgyNDBxMTcgMCAyOC41IDExLjVUNjAwLTQ0MHYxMjBoNDBxMjYgMC" +
            "A0NyAxNS41dDI5IDQwLjVaIiBmaWxsPSIjOWMzNmI1Ii8+PC9zdmc+PC9zdmc+",
        // route53 -> Material Symbols "travel_explore"
        "route53":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiM5YzM2YjUiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC04MHEtOD" +
            "MgMC0xNTYtMzEuNVQxOTctMTk3cS01NC01NC04NS41LTEyN1Q4MC00ODBxMC04MyAzMS41LTE1NlQxOTctNzYzcTU0LTU0IDEyNy" +
            "04NS41VDQ4MC04ODBxMTQ2IDAgMjU1LjUgOTEuNVQ4NzItNTU5aC04MnEtMTktNzMtNjguNS0xMzAuNVQ2MDAtNzc2djE2cTAgMz" +
            "MtMjMuNSA1Ni41VDUyMC02ODBoLTgwdjgwcTAgMTctMTEuNSAyOC41VDQwMC01NjBoLTgwdjgwaDgwdjEyMGgtNDBMMTY4LTU1Mn" +
            "EtMyAxOC01LjUgMzZ0LTIuNSAzNnEwIDEzMSA5MiAyMjV0MjI4IDk1djgwWm0zNjQtMjBMNzE2LTIyOHEtMjEgMTItNDUgMjB0LT" +
            "UxIDhxLTc1IDAtMTI3LjUtNTIuNVQ0NDAtMzgwcTAtNzUgNTIuNS0xMjcuNVQ2MjAtNTYwcTc1IDAgMTI3LjUgNTIuNVQ4MDAtMz" +
            "gwcTAgMjctOCA1MXQtMjAgNDVsMTI4IDEyOC01NiA1NlpNNjIwLTI4MHE0MiAwIDcxLTI5dDI5LTcxcTAtNDItMjktNzF0LTcxLT" +
            "I5cS00MiAwLTcxIDI5dC0yOSA3MXEwIDQyIDI5IDcxdDcxIDI5WiIgZmlsbD0iIzljMzZiNSIvPjwvc3ZnPjwvc3ZnPg==",
        // s3 -> Material Symbols "inventory_2"
        "s3":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMyZjllNDQiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTIwMC04MHEtMz" +
            "MgMC01Ni41LTIzLjVUMTIwLTE2MHYtNDUxcS0xOC0xMS0yOS0yOC41VDgwLTY4MHYtMTIwcTAtMzMgMjMuNS01Ni41VDE2MC04OD" +
            "BoNjQwcTMzIDAgNTYuNSAyMy41VDg4MC04MDB2MTIwcTAgMjMtMTEgNDAuNVQ4NDAtNjExdjQ1MXEwIDMzLTIzLjUgNTYuNVQ3Nj" +
            "AtODBIMjAwWm0tNDAtNjAwaDY0MHYtMTIwSDE2MHYxMjBabTIwMCAyODBoMjQwdi04MEgzNjB2ODBaIiBmaWxsPSIjMmY5ZTQ0Ii" +
            "8+PC9zdmc+PC9zdmc+",
        // rds -> Material Symbols "storage"
        "rds":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMyZjllNDQiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTEyMC0xNjB2LT" +
            "E2MGg3MjB2MTYwSDEyMFptODAtNDBoODB2LTgwaC04MHY4MFptLTgwLTQ0MHYtMTYwaDcyMHYxNjBIMTIwWm04MC00MGg4MHYtOD" +
            "BoLTgwdjgwWm0tODAgMjgwdi0xNjBoNzIwdjE2MEgxMjBabTgwLTQwaDgwdi04MGgtODB2ODBaIiBmaWxsPSIjMmY5ZTQ0Ii8+PC" +
            "9zdmc+PC9zdmc+",
        // dynamodb -> Material Symbols "table_chart"
        "dynamodb":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMyZjllNDQiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTEyMC02NDB2LT" +
            "EyMHEwLTMzIDIzLjUtNTYuNVQyMDAtODQwaDU2MHEzMyAwIDU2LjUgMjMuNVQ4NDAtNzYwdjEyMEgxMjBabTgwIDUyMHEtMzMgMC" +
            "01Ni41LTIzLjVUMTIwLTIwMHYtMzYwaDE4MHY0NDBIMjAwWm00NjAgMHYtNDQwaDE4MHYzNjBxMCAzMy0yMy41IDU2LjVUNzYwLT" +
            "EyMEg2NjBabS0yODAgMHYtNDQwaDIwMHY0NDBIMzgwWiIgZmlsbD0iIzJmOWU0NCIvPjwvc3ZnPjwvc3ZnPg==",
        // elasticache -> Material Symbols "speed"
        "elasticache":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMyZjllNDQiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQxOC0zNDBxMj" +
            "UgMjUgNjMgMjMuNXQ1NS0yNy41bDIyNC0zMzYtMzM2IDIyNHEtMjYgMTgtMjguNSA1NC41VDQxOC0zNDBaTTIwNC0xNjBxLTIyID" +
            "AtNDAuNS05LjVUMTM0LTE5OHEtMjYtNDctNDAtOTcuNVQ4MC00MDBxMC04MyAzMS41LTE1NlQxOTctNjgzcTU0LTU0IDEyNy04NS" +
            "41VDQ4MC04MDBxODIgMCAxNTQgMzF0MTI2IDg0LjVxNTQgNTMuNSA4NiAxMjVUODc5LTQwNnExIDU1LTEyLjUgMTA3LjVUODI1LT" +
            "E5OHEtMTEgMTktMjkuNSAyOC41VDc1NS0xNjBIMjA0WiIgZmlsbD0iIzJmOWU0NCIvPjwvc3ZnPjwvc3ZnPg==",
        // sqs -> Material Symbols "forum"
        "sqs":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNmMDhjMDAiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTI4MC0yNDBxLT" +
            "E3IDAtMjguNS0xMS41VDI0MC0yODB2LTgwaDUyMHYtMzYwaDgwcTE3IDAgMjguNSAxMS41VDg4MC02ODB2NjAwTDcyMC0yNDBIMj" +
            "gwWk04MC0yODB2LTU2MHEwLTE3IDExLjUtMjguNVQxMjAtODgwaDUyMHExNyAwIDI4LjUgMTEuNVQ2ODAtODQwdjM2MHEwIDE3LT" +
            "ExLjUgMjguNVQ2NDAtNDQwSDI0MEw4MC0yODBaIiBmaWxsPSIjZjA4YzAwIi8+PC9zdmc+PC9zdmc+",
        // sns -> Material Symbols "campaign"
        "sns":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNmMDhjMDAiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTcyMC00NDB2LT" +
            "gwaDE2MHY4MEg3MjBabTQ4IDI4MC0xMjgtOTYgNDgtNjQgMTI4IDk2LTQ4IDY0Wm0tODAtNDgwLTQ4LTY0IDEyOC05NiA0OCA2NC" +
            "0xMjggOTZaTTIwMC0yMDB2LTE2MGgtNDBxLTMzIDAtNTYuNS0yMy41VDgwLTQ0MHYtODBxMC0zMyAyMy41LTU2LjVUMTYwLTYwMG" +
            "gxNjBsMjAwLTEyMHY0ODBMMzIwLTM2MGgtNDB2MTYwaC04MFptMzYwLTE0NnYtMjY4cTI3IDI0IDQzLjUgNTguNVQ2MjAtNDgwcT" +
            "AgNDEtMTYuNSA3NS41VDU2MC0zNDZaIiBmaWxsPSIjZjA4YzAwIi8+PC9zdmc+PC9zdmc+",
        // eventbridge -> Material Symbols "shuffle"
        "eventbridge":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNmMDhjMDAiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTU2MC0xNjB2LT" +
            "gwaDEwNEw1MzctMzY3bDU3LTU3IDEyNiAxMjZ2LTEwMmg4MHYyNDBINTYwWm0tMzQ0IDAtNTYtNTYgNTA0LTUwNEg1NjB2LTgwaD" +
            "I0MHYyNDBoLTgwdi0xMDRMMjE2LTE2MFptMTUxLTM3N0wxNjAtNzQ0bDU2LTU2IDIwNyAyMDctNTYgNTZaIiBmaWxsPSIjZjA4Yz" +
            "AwIi8+PC9zdmc+PC9zdmc+",
        // kinesis -> Material Symbols "waves"
        "kinesis":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNmMDhjMDAiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTgwLTE0NnYtNz" +
            "hxMjkgMCA0OS41LTl0NDEuNS0xOS41cTIxLTEwLjUgNDYuNS0xOVQyODAtMjgwcTM4IDAgNjIuNSA4LjV0NDUuNSAxOXEyMSAxMC" +
            "41IDQyIDE5LjV0NTAgOXEyOSAwIDUwLTl0NDItMTkuNXEyMS0xMC41IDQ2LTE5dDYyLTguNXEzOCAwIDYzIDguNXQ0NiAxOXEyMS" +
            "AxMC41IDQyIDE5LjV0NDkgOXY3OHEtMzggMC02My41LTlUNzcwLTE3NC41cS0yMS0xMC41LTQxLTE5dC00OS04LjVxLTI4IDAtND" +
            "guNSA4LjV0LTQxIDE5UTU3MC0xNjQgNTQ0LjUtMTU1dC02NC41IDlxLTM5IDAtNjQuNS05dC00Ni0xOS41UTM0OS0xODUgMzI5LT" +
            "E5My41dC00OS04LjVxLTI4IDAtNDguNSA4LjV0LTQxLjUgMTlRMTY5LTE2NCAxNDMuNS0xNTVUODAtMTQ2Wm0wLTE3OHYtNzhxMj" +
            "kgMCA0OS41LTl0NDEuNS0xOS41cTIxLTEwLjUgNDYuNS0xOVQyODAtNDU4cTM4IDAgNjIuNSA4LjV0NDUuNSAxOXEyMSAxMC41ID" +
            "QyIDE5LjV0NTAgOXEyOSAwIDUwLTl0NDItMTkuNXEyMS0xMC41IDQ2LTE5dDYyLTguNXEzOCAwIDYzIDguNXQ0NiAxOXEyMSAxMC" +
            "41IDQyIDE5LjV0NDkgOXY3OHEtMzggMC02My41LTlUNzcwLTM1Mi41cS0yMS0xMC41LTQxLTE5dC00OS04LjVxLTI5IDAtNDkuNS" +
            "A4LjV0LTQxIDE5UTU2OS0zNDIgNTQ0LTMzM3QtNjQgOXEtMzkgMC02NC41LTl0LTQ2LTE5LjVRMzQ5LTM2MyAzMjktMzcxLjV0LT" +
            "Q5LTguNXEtMjggMC00OC41IDguNXQtNDEuNSAxOVExNjktMzQyIDE0My41LTMzM1Q4MC0zMjRabTAtMTc4di03OHEyOSAwIDQ5Lj" +
            "UtOXQ0MS41LTE5LjVxMjEtMTAuNSA0Ni41LTE5VDI4MC02MzZxMzggMCA2Mi41IDguNXQ0NS41IDE5cTIxIDEwLjUgNDIgMTkuNX" +
            "Q1MCA5cTI5IDAgNTAtOXQ0Mi0xOS41cTIxLTEwLjUgNDYtMTl0NjItOC41cTM4IDAgNjMgOC41dDQ2IDE5cTIxIDEwLjUgNDIgMT" +
            "kuNXQ0OSA5djc4cS0zOCAwLTYzLjUtOVQ3NzAtNTMwLjVxLTIxLTEwLjUtNDEtMTl0LTQ5LTguNXEtMjggMC00OC41IDguNXQtND" +
            "EgMTlRNTcwLTUyMCA1NDQuNS01MTF0LTY0LjUgOXEtMzkgMC02NC41LTl0LTQ2LTE5LjVRMzQ5LTU0MSAzMjktNTQ5LjV0LTQ5LT" +
            "guNXEtMjggMC00OC41IDguNXQtNDEuNSAxOVExNjktNTIwIDE0My41LTUxMVQ4MC01MDJabTAtMTc4di03OHEyOSAwIDQ5LjUtOX" +
            "Q0MS41LTE5LjVxMjEtMTAuNSA0Ni41LTE5VDI4MC04MTRxMzggMCA2Mi41IDguNXQ0NS41IDE5cTIxIDEwLjUgNDIgMTkuNXQ1MC" +
            "A5cTI5IDAgNTAtOXQ0Mi0xOS41cTIxLTEwLjUgNDYtMTl0NjItOC41cTM4IDAgNjMgOC41dDQ2IDE5cTIxIDEwLjUgNDIgMTkuNX" +
            "Q0OSA5djc4cS0zOCAwLTYzLjUtOVQ3NzAtNzA4LjVxLTIxLTEwLjUtNDEtMTl0LTQ5LTguNXEtMjggMC00OC41IDguNXQtNDEgMT" +
            "lRNTcwLTY5OCA1NDQuNS02ODl0LTY0LjUgOXEtMzkgMC02NC41LTl0LTQ2LTE5LjVRMzQ5LTcxOSAzMjktNzI3LjV0LTQ5LTguNX" +
            "EtMjggMC00OC41IDguNXQtNDEuNSAxOVExNjktNjk4IDE0My41LTY4OVQ4MC02ODBaIiBmaWxsPSIjZjA4YzAwIi8+PC9zdmc+PC" +
            "9zdmc+",
        // stepfunctions -> Material Symbols "account_tree"
        "stepfunctions":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNmMDhjMDAiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTYwMC0xMjB2LT" +
            "EyMEg0NDB2LTQwMGgtODB2MTIwSDgwdi0zMjBoMjgwdjEyMGgyNDB2LTEyMGgyODB2MzIwSDYwMHYtMTIwaC04MHYzMjBoODB2LT" +
            "EyMGgyODB2MzIwSDYwMFoiIGZpbGw9IiNmMDhjMDAiLz48L3N2Zz48L3N2Zz4=",
        // iam -> Material Symbols "badge"
        "iam":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNlMDMxMzEiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTE2MC04MHEtMz" +
            "MgMC01Ni41LTIzLjVUODAtMTYwdi00NDBxMC0zMyAyMy41LTU2LjVUMTYwLTY4MGgyMDB2LTEyMHEwLTMzIDIzLjUtNTYuNVQ0ND" +
            "AtODgwaDgwcTMzIDAgNTYuNSAyMy41VDYwMC04MDB2MTIwaDIwMHEzMyAwIDU2LjUgMjMuNVQ4ODAtNjAwdjQ0MHEwIDMzLTIzLj" +
            "UgNTYuNVQ4MDAtODBIMTYwWm04MC0xNjBoMjQwdi0xOHEwLTE3LTkuNS0zMS41VDQ0NC0zMTJxLTIwLTktNDAuNS0xMy41VDM2MC" +
            "0zMzBxLTIzIDAtNDMuNSA0LjVUMjc2LTMxMnEtMTcgOC0yNi41IDIyLjVUMjQwLTI1OHYxOFptMzIwLTYwaDE2MHYtNjBINTYwdj" +
            "YwWm0tMjAwLTYwcTI1IDAgNDIuNS0xNy41VDQyMC00MjBxMC0yNS0xNy41LTQyLjVUMzYwLTQ4MHEtMjUgMC00Mi41IDE3LjVUMz" +
            "AwLTQyMHEwIDI1IDE3LjUgNDIuNVQzNjAtMzYwWm0yMDAtNjBoMTYwdi02MEg1NjB2NjBaTTQ0MC02MDBoODB2LTIwMGgtODB2Mj" +
            "AwWiIgZmlsbD0iI2UwMzEzMSIvPjwvc3ZnPjwvc3ZnPg==",
        // secretsmanager -> Material Symbols "key"
        "secretsmanager":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNlMDMxMzEiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTI4MC0zNjBxNT" +
            "AgMCA4NS0zNXQzNS04NXEwLTUwLTM1LTg1dC04NS0zNXEtNTAgMC04NSAzNXQtMzUgODVxMCA1MCAzNSA4NXQ4NSAzNVptMCAxMj" +
            "BxLTEwMCAwLTE3MC03MFQ0MC00ODBxMC0xMDAgNzAtMTcwdDE3MC03MHE4MSAwIDE0MS41IDQ2VDUwNi01NjBoMzM1bDc5IDc5LT" +
            "E0MCAxNjAtMTAwLTc5LTgwIDgwLTgwLTgwaC0xNHEtMjUgNzItODcgMTE2dC0xMzkgNDRaIiBmaWxsPSIjZTAzMTMxIi8+PC9zdm" +
            "c+PC9zdmc+",
        // cloudwatch -> Material Symbols "visibility"
        "cloudwatch":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwY2E2NzgiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC0zMjBxNz" +
            "UgMCAxMjcuNS01Mi41VDY2MC01MDBxMC03NS01Mi41LTEyNy41VDQ4MC02ODBxLTc1IDAtMTI3LjUgNTIuNVQzMDAtNTAwcTAgNz" +
            "UgNTIuNSAxMjcuNVQ0ODAtMzIwWm0wLTcycS00NSAwLTc2LjUtMzEuNVQzNzItNTAwcTAtNDUgMzEuNS03Ni41VDQ4MC02MDhxND" +
            "UgMCA3Ni41IDMxLjVUNTg4LTUwMHEwIDQ1LTMxLjUgNzYuNVQ0ODAtMzkyWm0wIDE5MnEtMTQ2IDAtMjY2LTgxLjVUNDAtNTAwcT" +
            "U0LTEzNyAxNzQtMjE4LjVUNDgwLTgwMHExNDYgMCAyNjYgODEuNVQ5MjAtNTAwcS01NCAxMzctMTc0IDIxOC41VDQ4MC0yMDBaIi" +
            "BmaWxsPSIjMGNhNjc4Ii8+PC9zdmc+PC9zdmc+",
        // vpc -> Material Symbols "account_balance"
        "vpc":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMzNDNhNDAiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTIwMC0yODB2LT" +
            "I4MGg4MHYyODBoLTgwWm0yNDAgMHYtMjgwaDgwdjI4MGgtODBaTTgwLTEyMHYtODBoODAwdjgwSDgwWm02MDAtMTYwdi0yODBoOD" +
            "B2MjgwaC04MFpNODAtNjQwdi04MGw0MDAtMjAwIDQwMCAyMDB2ODBIODBaIiBmaWxsPSIjMzQzYTQwIi8+PC9zdmc+PC9zdmc+",
        // deploy -> Material Symbols "rocket_launch"
        "deploy":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwYzg1OTkiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0ibTk4LTUzNyAxNj" +
            "gtMTY4cTE0LTE0IDMzLTIwdDM5LTJsNTIgMTFxLTU0IDY0LTg1IDExNnQtNjAgMTI2TDk4LTUzN1ptMjA1IDkxcTIzLTcyIDYyLj" +
            "UtMTM2VDQ2MS03MDJxODgtODggMjAxLTEzMS41VDg3My04NjBxMTcgOTgtMjYgMjExVDcxNi00NDhxLTU1IDU1LTEyMCA5NS41VD" +
            "Q1OS0yODlMMzAzLTQ0NlptMjc2LTEyMHEyMyAyMyA1Ni41IDIzdDU2LjUtMjNxMjMtMjMgMjMtNTYuNVQ2OTItNjc5cS0yMy0yMy" +
            "01Ni41LTIzVDU3OS02NzlxLTIzIDIzLTIzIDU2LjV0MjMgNTYuNVpNNTUxLTg1bC02NC0xNDdxNzQtMjkgMTI2LjUtNjBUNzMwLT" +
            "M3N2wxMCA1MnE0IDIwLTIgMzkuNVQ3MTgtMjUyTDU1MS04NVpNMTYyLTMxOHEzNS0zNSA4NS0zNS41dDg1IDM0LjVxMzUgMzUgMz" +
            "UgODV0LTM1IDg1cS0yNSAyNS04My41IDQzVDg3LTc0cTE0LTEwMyAzMi0xNjF0NDMtODNaIiBmaWxsPSIjMGM4NTk5Ii8+PC9zdm" +
            "c+PC9zdmc+",
        // k8ssvc -> Material Symbols "share"
        "k8ssvc":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiM5YzM2YjUiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTcyMC04MHEtNT" +
            "AgMC04NS0zNXQtMzUtODVxMC03IDEtMTQuNXQzLTEzLjVMMzIyLTM5MnEtMTcgMTUtMzggMjMuNXQtNDQgOC41cS01MCAwLTg1LT" +
            "M1dC0zNS04NXEwLTUwIDM1LTg1dDg1LTM1cTIzIDAgNDQgOC41dDM4IDIzLjVsMjgyLTE2NHEtMi02LTMtMTMuNXQtMS0xNC41cT" +
            "AtNTAgMzUtODV0ODUtMzVxNTAgMCA4NSAzNXQzNSA4NXEwIDUwLTM1IDg1dC04NSAzNXEtMjMgMC00NC04LjVUNjM4LTY3MkwzNT" +
            "YtNTA4cTIgNiAzIDEzLjV0MSAxNC41cTAgNy0xIDE0LjV0LTMgMTMuNWwyODIgMTY0cTE3LTE1IDM4LTIzLjV0NDQtOC41cTUwID" +
            "AgODUgMzV0MzUgODVxMCA1MC0zNSA4NXQtODUgMzVaIiBmaWxsPSIjOWMzNmI1Ii8+PC9zdmc+PC9zdmc+",
        // ingress -> Material Symbols "route"
        "ingress":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiM5YzM2YjUiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTM2MC0xMjBxLT" +
            "Y2IDAtMTEzLTQ3dC00Ny0xMTN2LTMyN3EtMzUtMTMtNTcuNS00My41VDEyMC03MjBxMC01MCAzNS04NXQ4NS0zNXE1MCAwIDg1ID" +
            "M1dDM1IDg1cTAgMzktMjIuNSA2OS41VDI4MC02MDd2MzI3cTAgMzMgMjMuNSA1Ni41VDM2MC0yMDBxMzMgMCA1Ni41LTIzLjVUND" +
            "QwLTI4MHYtNDAwcTAtNjYgNDctMTEzdDExMy00N3E2NiAwIDExMyA0N3Q0NyAxMTN2MzI3cTM1IDEzIDU3LjUgNDMuNVQ4NDAtMj" +
            "QwcTAgNTAtMzUgODV0LTg1IDM1cS01MCAwLTg1LTM1dC0zNS04NXEwLTM5IDIyLjUtNzB0NTcuNS00M3YtMzI3cTAtMzMtMjMuNS" +
            "01Ni41VDYwMC03NjBxLTMzIDAtNTYuNSAyMy41VDUyMC02ODB2NDAwcTAgNjYtNDcgMTEzdC0xMTMgNDdaIiBmaWxsPSIjOWMzNm" +
            "I1Ii8+PC9zdmc+PC9zdmc+",
        // configmap -> Material Symbols "description"
        "configmap":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMyZjllNDQiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTMyMC0yNDBoMz" +
            "Iwdi04MEgzMjB2ODBabTAtMTYwaDMyMHYtODBIMzIwdjgwWk0yNDAtODBxLTMzIDAtNTYuNS0yMy41VDE2MC0xNjB2LTY0MHEwLT" +
            "MzIDIzLjUtNTYuNVQyNDAtODgwaDMyMGwyNDAgMjQwdjQ4MHEwIDMzLTIzLjUgNTYuNVQ3MjAtODBIMjQwWm0yODAtNTIwaDIwME" +
            "w1MjAtODAwdjIwMFoiIGZpbGw9IiMyZjllNDQiLz48L3N2Zz48L3N2Zz4=",
        // namespace -> Material Symbols "folder_managed"
        "namespace":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMzNDNhNDAiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0ibTY4MC04MC0xMi" +
            "02MHEtMTItNS0yMi41LTEwLjVUNjI0LTE2NGwtNTggMTgtNDAtNjggNDYtNDBxLTItMTItMi0yNnQyLTI2bC00Ni00MCA0MC02OC" +
            "A1OCAxOHExMS04IDIxLjUtMTMuNVQ2NjgtNDIwbDEyLTYwaDgwbDEyIDYwcTEyIDUgMjIuNSAxMC41VDgxNi0zOTZsNTgtMTggND" +
            "AgNjgtNDYgNDBxMiAxMiAyIDI2dC0yIDI2bDQ2IDQwLTQwIDY4LTU4LTE4cS0xMSA4LTIxLjUgMTMuNVQ3NzItMTQwbC0xMiA2MG" +
            "gtODBabTQwLTEyMHEzMyAwIDU2LjUtMjMuNVQ4MDAtMjgwcTAtMzMtMjMuNS01Ni41VDcyMC0zNjBxLTMzIDAtNTYuNSAyMy41VD" +
            "Y0MC0yODBxMCAzMyAyMy41IDU2LjVUNzIwLTIwMFptLTU2MCA0MHEtMzMgMC01Ni41LTIzLjVUODAtMjQwdi00ODBxMC0zMyAyMy" +
            "41LTU2LjVUMTYwLTgwMGgyNDBsODAgODBoMzIwcTMzIDAgNTYuNSAyMy41VDg4MC02NDB2MTMxcS0zNS0yNS03Ni0zOHQtODUtMT" +
            "NxLTExOCAwLTE5OC41IDgyLjVUNDQwLTI4MXEwIDMyIDcgNjJ0MjEgNTlIMTYwWiIgZmlsbD0iIzM0M2E0MCIvPjwvc3ZnPjwvc3" +
            "ZnPg==",
        // statefulset -> Material Symbols "layers"
        "statefulset":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwYzg1OTkiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC0xMTggMT" +
            "IwLTM5OGw2Ni01MCAyOTQgMjI4IDI5NC0yMjggNjYgNTAtMzYwIDI4MFptMC0yMDJMMTIwLTYwMGwzNjAtMjgwIDM2MCAyODAtMz" +
            "YwIDI4MFoiIGZpbGw9IiMwYzg1OTkiLz48L3N2Zz48L3N2Zz4=",
        // cronjob -> Material Symbols "schedule"
        "cronjob":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwYzg1OTkiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0ibTYxMi0yOTIgNT" +
            "YtNTYtMTQ4LTE0OHYtMTg0aC04MHYyMTZsMTcyIDE3MlpNNDgwLTgwcS04MyAwLTE1Ni0zMS41VDE5Ny0xOTdxLTU0LTU0LTg1Lj" +
            "UtMTI3VDgwLTQ4MHEwLTgzIDMxLjUtMTU2VDE5Ny03NjNxNTQtNTQgMTI3LTg1LjVUNDgwLTg4MHE4MyAwIDE1NiAzMS41VDc2My" +
            "03NjNxNTQgNTQgODUuNSAxMjdUODgwLTQ4MHEwIDgzLTMxLjUgMTU2VDc2My0xOTdxLTU0IDU0LTEyNyA4NS41VDQ4MC04MFoiIG" +
            "ZpbGw9IiMwYzg1OTkiLz48L3N2Zz48L3N2Zz4=",
        // node -> Material Symbols "developer_board"
        "node":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMxOTcxYzIiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTE2MC0xMjBxLT" +
            "MzIDAtNTYuNS0yMy41VDgwLTIwMHYtNTYwcTAtMzMgMjMuNS01Ni41VDE2MC04NDBoNTYwcTMzIDAgNTYuNSAyMy41VDgwMC03Nj" +
            "B2ODBoODB2ODBoLTgwdjgwaDgwdjgwaC04MHY4MGg4MHY4MGgtODB2ODBxMCAzMy0yMy41IDU2LjVUNzIwLTEyMEgxNjBabTgwLT" +
            "E2MGgyMDB2LTE2MEgyNDB2MTYwWm0yNDAtMjgwaDE2MHYtMTIwSDQ4MHYxMjBabS0yNDAgODBoMjAwdi0yMDBIMjQwdjIwMFptMj" +
            "QwIDIwMGgxNjB2LTI0MEg0ODB2MjQwWiIgZmlsbD0iIzE5NzFjMiIvPjwvc3ZnPjwvc3ZnPg==",
        // cdn -> Material Symbols "cell_tower"
        "cdn":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiM5YzM2YjUiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTE5Ni0yNzZxLT" +
            "U3LTYwLTg2LjUtMTMzVDgwLTU2MHEwLTc4IDI5LjUtMTUxVDE5Ni04NDRsNDggNDhxLTQ4IDQ4LTcyIDExMC41VDE0OC01NjBxMC" +
            "A2MyAyNCAxMjUuNVQyNDQtMzI0bC00OCA0OFptOTYtOTZxLTM5LTM5LTU5LjUtODhUMjEyLTU2MHEwLTUxIDIwLjUtMTAwdDU5Lj" +
            "UtODhsNDggNDhxLTMwIDI3LTQ1IDY0dC0xNSA3NnEwIDM2IDE1IDczdDQ1IDY3bC00OCA0OFpNMjgwLTgwbDEzNS00MDVxLTE2LT" +
            "E0LTI1LjUtMzN0LTkuNS00MnEwLTQyIDI5LTcxdDcxLTI5cTQyIDAgNzEgMjl0MjkgNzFxMCAyMy05LjUgNDJUNTQ1LTQ4NUw2OD" +
            "AtODBoLTgwbC0yNi04MEgzODdsLTI3IDgwaC04MFptMTMzLTE2MGgxMzRsLTY3LTIwMC02NyAyMDBabTI1NS0xMzItNDgtNDhxMz" +
            "AtMjcgNDUtNjR0MTUtNzZxMC0zNi0xNS03M3QtNDUtNjdsNDgtNDhxMzkgMzkgNTggODh0MjIgMTAwcTAgNTEtMjAuNSAxMDBUNj" +
            "Y4LTM3MlptOTYgOTYtNDgtNDhxNDgtNDggNzItMTEwLjVUODEyLTU2MHEwLTYzLTI0LTEyNS41VDcxNi03OTZsNDgtNDhxNTcgNj" +
            "AgODYuNSAxMzNUODgwLTU2MHEwIDc4LTI4IDE1MXQtODggMTMzWiIgZmlsbD0iIzljMzZiNSIvPjwvc3ZnPjwvc3ZnPg==",
        // dns -> Material Symbols "language"
        "dns":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiM5YzM2YjUiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC04MHEtOD" +
            "IgMC0xNTUtMzEuNXQtMTI3LjUtODZRMTQzLTI1MiAxMTEuNS0zMjVUODAtNDgwcTAtODMgMzEuNS0xNTUuNXQ4Ni0xMjdRMjUyLT" +
            "gxNyAzMjUtODQ4LjVUNDgwLTg4MHE4MyAwIDE1NS41IDMxLjV0MTI3IDg2cTU0LjUgNTQuNSA4NiAxMjdUODgwLTQ4MHEwIDgyLT" +
            "MxLjUgMTU1dC04NiAxMjcuNXEtNTQuNSA1NC41LTEyNyA4NlQ0ODAtODBabTAtODJxMjYtMzYgNDUtNzV0MzEtODNINDA0cTEyID" +
            "Q0IDMxIDgzdDQ1IDc1Wm0tMTA0LTE2cS0xOC0zMy0zMS41LTY4LjVUMzIyLTMyMEgyMDRxMjkgNTAgNzIuNSA4N3Q5OS41IDU1Wm" +
            "0yMDggMHE1Ni0xOCA5OS41LTU1dDcyLjUtODdINjM4cS05IDM4LTIyLjUgNzMuNVQ1ODQtMTc4Wk0xNzAtNDAwaDEzNnEtMy0yMC" +
            "00LjUtMzkuNVQzMDAtNDgwcTAtMjEgMS41LTQwLjVUMzA2LTU2MEgxNzBxLTUgMjAtNy41IDM5LjVUMTYwLTQ4MHEwIDIxIDIuNS" +
            "A0MC41VDE3MC00MDBabTIxNiAwaDE4OHEzLTIwIDQuNS0zOS41VDU4MC00ODBxMC0yMS0xLjUtNDAuNVQ1NzQtNTYwSDM4NnEtMy" +
            "AyMC00LjUgMzkuNVQzODAtNDgwcTAgMjEgMS41IDQwLjVUMzg2LTQwMFptMjY4IDBoMTM2cTUtMjAgNy41LTM5LjVUODAwLTQ4MH" +
            "EwLTIxLTIuNS00MC41VDc5MC01NjBINjU0cTMgMjAgNC41IDM5LjVUNjYwLTQ4MHEwIDIxLTEuNSA0MC41VDY1NC00MDBabS0xNi" +
            "0yNDBoMTE4cS0yOS01MC03Mi41LTg3VDU4NC03ODJxMTggMzMgMzEuNSA2OC41VDYzOC02NDBabS0yMzQgMGgxNTJxLTEyLTQ0LT" +
            "MxLTgzdC00NS03NXEtMjYgMzYtNDUgNzV0LTMxIDgzWm0tMjAwIDBoMTE4cTktMzggMjIuNS03My41VDM3Ni03ODJxLTU2IDE4LT" +
            "k5LjUgNTVUMjA0LTY0MFoiIGZpbGw9IiM5YzM2YjUiLz48L3N2Zz48L3N2Zz4=",
        // firewall -> Material Symbols "security"
        "firewall":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNlMDMxMzEiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC04MHEtMT" +
            "M5LTM1LTIyOS41LTE1OS41VDE2MC01MTZ2LTI0NGwzMjAtMTIwIDMyMCAxMjB2MjQ0cTAgMTUyLTkwLjUgMjc2LjVUNDgwLTgwWm" +
            "0wLTg0cTk3LTMwIDE2Mi0xMTguNVQ3MTgtNDgwSDQ4MHYtMzE1bC0yNDAgOTB2MjA3cTAgNyAyIDE4aDIzOHYzMTZaIiBmaWxsPS" +
            "IjZTAzMTMxIi8+PC9zdmc+PC9zdmc+",
        // proxy -> Material Symbols "swap_calls"
        "proxy":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiM5YzM2YjUiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTI0MC0yMDAgOD" +
            "AtMzYwbDU2LTU4IDY0IDY0di0yODZxMC02NiA0Ny0xMTN0MTEzLTQ3cTY2IDAgMTEzIDQ3dDQ3IDExM3YyODBxMCAzMyAyMy41ID" +
            "U2LjVUNjAwLTI4MHEzMyAwIDU2LjUtMjMuNVQ2ODAtMzYwdi0yODZsLTY0IDY0LTU2LTU4IDE2MC0xNjAgMTYwIDE2MC01NiA1OC" +
            "02NC02NHYyODZxMCA2Ni00NyAxMTN0LTExMyA0N3EtNjYgMC0xMTMtNDd0LTQ3LTExM3YtMjgwcTAtMzMtMjMuNS01Ni41VDM2MC" +
            "03MjBxLTMzIDAtNTYuNSAyMy41VDI4MC02NDB2Mjg2bDY0LTY0IDU2IDU4LTE2MCAxNjBaIiBmaWxsPSIjOWMzNmI1Ii8+PC9zdm" +
            "c+PC9zdmc+",
        // vpn -> Material Symbols "vpn_lock"
        "vpn":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNlMDMxMzEiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC04MHEtOD" +
            "IgMC0xNTUtMzEuNXQtMTI3LjUtODZRMTQzLTI1MiAxMTEuNS0zMjVUODAtNDgwcTAtODMgMzEuNS0xNTUuNXQ4Ni0xMjdRMjUyLT" +
            "gxNyAzMjUtODQ4LjVUNDgwLTg4MHEzMiAwIDYxLjUgNC41VDYwMC04NjJ2MTAycTAgMzMtMjMuNSA1Ni41VDUyMC02ODBoLTgwdj" +
            "gwcTAgMTctMTEuNSAyOC41VDQwMC01NjBoLTgwdjgwaDI0MHExNyAwIDI4LjUgMTEuNVQ2MDAtNDQwdjEyMGg0MHEyNyAwIDQ3Lj" +
            "UgMTZ0MjguNSA0MHEzOS00NCA2MS41LTk4LjVUODAwLTQ4MHEwLTExLTEtMjB0LTMtMjBoODJxMiAxMSAyIDIwdjIwcTAgODItMz" +
            "EuNSAxNTV0LTg2IDEyNy41cS01NC41IDU0LjUtMTI3IDg2VDQ4MC04MFptLTQwLTgydi03OHEtMzMgMC01Ni41LTIzLjVUMzYwLT" +
            "MyMHYtNDBMMTY4LTU1MnEtMyAxOC01LjUgMzZ0LTIuNSAzNnEwIDEyNCA4MC41IDIxMy41VDQ0MC0xNjJabTI4MC00MzhxLTE3ID" +
            "AtMjguNS0xMS41VDY4MC02NDB2LTEyMHEwLTE3IDExLjUtMjguNVQ3MjAtODAwdi00MHEwLTMzIDIzLjUtNTYuNVQ4MDAtOTIwcT" +
            "MzIDAgNTYuNSAyMy41VDg4MC04NDB2NDBxMTcgMCAyOC41IDExLjVUOTIwLTc2MHYxMjBxMCAxNy0xMS41IDI4LjVUODgwLTYwME" +
            "g3MjBabTQwLTIwMGg4MHYtNDBxMC0xNy0xMS41LTI4LjVUODAwLTg4MHEtMTcgMC0yOC41IDExLjVUNzYwLTg0MHY0MFoiIGZpbG" +
            "w9IiNlMDMxMzEiLz48L3N2Zz48L3N2Zz4=",
        // internet -> Material Symbols "cloud"
        "internet":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMzNDNhNDAiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTI2MC0xNjBxLT" +
            "kxIDAtMTU1LjUtNjNUNDAtMzc3cTAtNzggNDctMTM5dDEyMy03OHEyNS05MiAxMDAtMTQ5dDE3MC01N3ExMTcgMCAxOTguNSA4MS" +
            "41VDc2MC01MjBxNjkgOCAxMTQuNSA1OS41VDkyMC0zNDBxMCA3NS01Mi41IDEyNy41VDc0MC0xNjBIMjYwWiIgZmlsbD0iIzM0M2" +
            "E0MCIvPjwvc3ZnPjwvc3ZnPg==",
        // subnet -> Material Symbols "map"
        "subnet":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMzNDNhNDAiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0ibTYwMC0xMjAtMj" +
            "QwLTg0LTE4NiA3MnEtMjAgOC0zNy00LjVUMTIwLTE3MHYtNTYwcTAtMTMgNy41LTIzdDIwLjUtMTVsMjEyLTcyIDI0MCA4NCAxOD" +
            "YtNzJxMjAtOCAzNyA0LjV0MTcgMzMuNXY1NjBxMCAxMy03LjUgMjNUODEyLTE5MmwtMjEyIDcyWm0tNDAtOTh2LTQ2OGwtMTYwLT" +
            "U2djQ2OGwxNjAgNTZaIiBmaWxsPSIjMzQzYTQwIi8+PC9zdmc+PC9zdmc+",
        // cache -> Material Symbols "memory"
        "cache":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMyZjllNDQiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTM2MC0zNjB2LT" +
            "I0MGgyNDB2MjQwSDM2MFptMCAyNDB2LTgwaC04MHEtMzMgMC01Ni41LTIzLjVUMjAwLTI4MHYtODBoLTgwdi04MGg4MHYtODBoLT" +
            "gwdi04MGg4MHYtODBxMC0zMyAyMy41LTU2LjVUMjgwLTc2MGg4MHYtODBoODB2ODBoODB2LTgwaDgwdjgwaDgwcTMzIDAgNTYuNS" +
            "AyMy41VDc2MC02ODB2ODBoODB2ODBoLTgwdjgwaDgwdjgwaC04MHY4MHEwIDMzLTIzLjUgNTYuNVQ2ODAtMjAwaC04MHY4MGgtOD" +
            "B2LTgwaC04MHY4MGgtODBabTMyMC0xNjB2LTQwMEgyODB2NDAwaDQwMFoiIGZpbGw9IiMyZjllNDQiLz48L3N2Zz48L3N2Zz4=",
        // blob -> Material Symbols "folder"
        "blob":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMyZjllNDQiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTE2MC0xNjBxLT" +
            "MzIDAtNTYuNS0yMy41VDgwLTI0MHYtNDgwcTAtMzMgMjMuNS01Ni41VDE2MC04MDBoMjQwbDgwIDgwaDMyMHEzMyAwIDU2LjUgMj" +
            "MuNVQ4ODAtNjQwdjQwMHEwIDMzLTIzLjUgNTYuNVQ4MDAtMTYwSDE2MFoiIGZpbGw9IiMyZjllNDQiLz48L3N2Zz48L3N2Zz4=",
        // warehouse -> Material Symbols "warehouse"
        "warehouse":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMyZjllNDQiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTgwLTEyMHYtNT" +
            "YwbDQwMC0xNjAgNDAwIDE2MHY1NjBINjQwdi0zMjBIMzIwdjMyMEg4MFptMjgwIDB2LTgwaDgwdjgwaC04MFptODAtMTIwdi04MG" +
            "g4MHY4MGgtODBabTgwIDEyMHYtODBoODB2ODBoLTgwWiIgZmlsbD0iIzJmOWU0NCIvPjwvc3ZnPjwvc3ZnPg==",
        // search -> Material Symbols "search"
        "search":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMyZjllNDQiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTc4NC0xMjAgNT" +
            "MyLTM3MnEtMzAgMjQtNjkgMzh0LTgzIDE0cS0xMDkgMC0xODQuNS03NS41VDEyMC01ODBxMC0xMDkgNzUuNS0xODQuNVQzODAtOD" +
            "QwcTEwOSAwIDE4NC41IDc1LjVUNjQwLTU4MHEwIDQ0LTE0IDgzdC0zOCA2OWwyNTIgMjUyLTU2IDU2Wk0zODAtNDAwcTc1IDAgMT" +
            "I3LjUtNTIuNVQ1NjAtNTgwcTAtNzUtNTIuNS0xMjcuNVQzODAtNzYwcS03NSAwLTEyNy41IDUyLjVUMjAwLTU4MHEwIDc1IDUyLj" +
            "UgMTI3LjVUMzgwLTQwMFoiIGZpbGw9IiMyZjllNDQiLz48L3N2Zz48L3N2Zz4=",
        // stream -> Material Symbols "sync_alt"
        "stream":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNmMDhjMDAiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTI4MC0xMjAgOD" +
            "AtMzIwbDIwMC0yMDAgNTcgNTYtMTA0IDEwNGg2MDd2ODBIMjMzbDEwNCAxMDQtNTcgNTZabTQwMC0zMjAtNTctNTYgMTA0LTEwNE" +
            "gxMjB2LTgwaDYwN0w2MjMtNzg0bDU3LTU2IDIwMCAyMDAtMjAwIDIwMFoiIGZpbGw9IiNmMDhjMDAiLz48L3N2Zz48L3N2Zz4=",
        // metrics -> Material Symbols "monitoring"
        "metrics":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwY2E2NzgiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTEyMC0xMjB2LT" +
            "gwbDgwLTgwdjE2MGgtODBabTE2MCAwdi0yNDBsODAtODB2MzIwaC04MFptMTYwIDB2LTMyMGw4MCA4MXYyMzloLTgwWm0xNjAgMH" +
            "YtMjM5bDgwLTgwdjMxOWgtODBabTE2MCAwdi00MDBsODAtODB2NDgwaC04MFpNMTIwLTMyN3YtMTEzbDI4MC0yODAgMTYwIDE2MC" +
            "AyODAtMjgwdjExM0w1NjAtNDQ3IDQwMC02MDcgMTIwLTMyN1oiIGZpbGw9IiMwY2E2NzgiLz48L3N2Zz48L3N2Zz4=",
        // logs -> Material Symbols "receipt_long"
        "logs":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwY2E2NzgiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTI0MC04MHEtNT" +
            "AgMC04NS0zNXQtMzUtODV2LTEyMGgxMjB2LTU2MGw2MCA2MCA2MC02MCA2MCA2MCA2MC02MCA2MCA2MCA2MC02MCA2MCA2MCA2MC" +
            "02MCA2MCA2MCA2MC02MHY2ODBxMCA1MC0zNSA4NXQtODUgMzVIMjQwWm00ODAtODBxMTcgMCAyOC41LTExLjVUNzYwLTIwMHYtNT" +
            "YwSDMyMHY0NDBoMzYwdjEyMHEwIDE3IDExLjUgMjguNVQ3MjAtMTYwWk0zNjAtNjAwdi04MGgyNDB2ODBIMzYwWm0wIDEyMHYtOD" +
            "BoMjQwdjgwSDM2MFptMzIwLTEyMHEtMTcgMC0yOC41LTExLjVUNjQwLTY0MHEwLTE3IDExLjUtMjguNVQ2ODAtNjgwcTE3IDAgMj" +
            "guNSAxMS41VDcyMC02NDBxMCAxNy0xMS41IDI4LjVUNjgwLTYwMFptMCAxMjBxLTE3IDAtMjguNS0xMS41VDY0MC01MjBxMC0xNy" +
            "AxMS41LTI4LjVUNjgwLTU2MHExNyAwIDI4LjUgMTEuNVQ3MjAtNTIwcTAgMTctMTEuNSAyOC41VDY4MC00ODBaIiBmaWxsPSIjMG" +
            "NhNjc4Ii8+PC9zdmc+PC9zdmc+",
        // traces -> Material Symbols "timeline"
        "traces":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwY2E2NzgiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTEyMC0yNDBxLT" +
            "MzIDAtNTYuNS0yMy41VDQwLTMyMHEwLTMzIDIzLjUtNTYuNVQxMjAtNDAwaDEwLjVxNC41IDAgOS41IDJsMTgyLTE4MnEtMi01LT" +
            "ItOS41Vi02MDBxMC0zMyAyMy41LTU2LjVUNDAwLTY4MHEzMyAwIDU2LjUgMjMuNVQ0ODAtNjAwcTAgMi0yIDIwbDEwMiAxMDJxNS" +
            "0yIDkuNS0yaDIxcTQuNSAwIDkuNSAybDE0Mi0xNDJxLTItNS0yLTkuNVYtNjQwcTAtMzMgMjMuNS01Ni41VDg0MC03MjBxMzMgMC" +
            "A1Ni41IDIzLjVUOTIwLTY0MHEwIDMzLTIzLjUgNTYuNVQ4NDAtNTYwaC0xMC41cS00LjUgMC05LjUtMkw2NzgtNDIwcTIgNSAyID" +
            "kuNXYxMC41cTAgMzMtMjMuNSA1Ni41VDYwMC0zMjBxLTMzIDAtNTYuNS0yMy41VDUyMC00MDB2LTEwLjVxMC00LjUgMi05LjVMND" +
            "IwLTUyMnEtNSAyLTkuNSAySDQwMHEtMiAwLTIwLTJMMTk4LTM0MHEyIDUgMiA5LjV2MTAuNXEwIDMzLTIzLjUgNTYuNVQxMjAtMj" +
            "QwWiIgZmlsbD0iIzBjYTY3OCIvPjwvc3ZnPjwvc3ZnPg==",
        // dashboard -> Material Symbols "dashboard"
        "dashboard":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwY2E2NzgiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTUyMC02MDB2LT" +
            "I0MGgzMjB2MjQwSDUyMFpNMTIwLTQ0MHYtNDAwaDMyMHY0MDBIMTIwWm00MDAgMzIwdi00MDBoMzIwdjQwMEg1MjBabS00MDAgMH" +
            "YtMjQwaDMyMHYyNDBIMTIwWiIgZmlsbD0iIzBjYTY3OCIvPjwvc3ZnPjwvc3ZnPg==",
        // alert -> Material Symbols "warning"
        "alert":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwY2E2NzgiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0ibTQwLTEyMCA0ND" +
            "AtNzYwIDQ0MCA3NjBINDBabTQ0MC0xMjBxMTcgMCAyOC41LTExLjVUNTIwLTI4MHEwLTE3LTExLjUtMjguNVQ0ODAtMzIwcS0xNy" +
            "AwLTI4LjUgMTEuNVQ0NDAtMjgwcTAgMTcgMTEuNSAyOC41VDQ4MC0yNDBabS00MC0xMjBoODB2LTIwMGgtODB2MjAwWiIgZmlsbD" +
            "0iIzBjYTY3OCIvPjwvc3ZnPjwvc3ZnPg==",
        // oncall -> Material Symbols "call"
        "oncall":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwY2E2NzgiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTc5OC0xMjBxLT" +
            "EyNSAwLTI0Ny01NC41VDMyOS0zMjlRMjI5LTQyOSAxNzQuNS01NTFUMTIwLTc5OHEwLTE4IDEyLTMwdDMwLTEyaDE2MnExNCAwID" +
            "I1IDkuNXQxMyAyMi41bDI2IDE0MHEyIDE2LTEgMjd0LTExIDE5bC05NyA5OHEyMCAzNyA0Ny41IDcxLjVUMzg3LTM4NnEzMSAzMS" +
            "A2NSA1Ny41dDcyIDQ4LjVsOTQtOTRxOS05IDIzLjUtMTMuNVQ2NzAtMzkwbDEzOCAyOHExNCA0IDIzIDE0LjV0OSAyMy41djE2Mn" +
            "EwIDE4LTEyIDMwdC0zMCAxMloiIGZpbGw9IiMwY2E2NzgiLz48L3N2Zz48L3N2Zz4=",
        // repo -> Material Symbols "book"
        "repo":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNjMjI1NWMiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTI0MC04MHEtMz" +
            "MgMC01Ni41LTIzLjVUMTYwLTE2MHYtNjQwcTAtMzMgMjMuNS01Ni41VDI0MC04ODBoNDgwcTMzIDAgNTYuNSAyMy41VDgwMC04MD" +
            "B2NjQwcTAgMzMtMjMuNSA1Ni41VDcyMC04MEgyNDBabTIwMC00NDAgMTAwLTYwIDEwMCA2MHYtMjgwSDQ0MHYyODBaIiBmaWxsPS" +
            "IjYzIyNTVjIi8+PC9zdmc+PC9zdmc+",
        // pipeline -> Material Symbols "build"
        "pipeline":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNjMjI1NWMiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTY4Ni0xMzIgND" +
            "Q0LTM3NnEtMjAgOC00MC41IDEydC00My41IDRxLTEwMCAwLTE3MC03MHQtNzAtMTcwcTAtMzYgMTAtNjguNXQyOC02MS41bDE0Ni" +
            "AxNDYgNzItNzItMTQ2LTE0NnEyOS0xOCA2MS41LTI4dDY4LjUtMTBxMTAwIDAgMTcwIDcwdDcwIDE3MHEwIDIzLTQgNDMuNVQ1OD" +
            "QtNTE2bDI0NCAyNDJxMTIgMTIgMTIgMjl0LTEyIDI5bC04NCA4NHEtMTIgMTItMjkgMTJ0LTI5LTEyWiIgZmlsbD0iI2MyMjU1Yy" +
            "IvPjwvc3ZnPjwvc3ZnPg==",
        // registry -> Material Symbols "apps"
        "registry":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNjMjI1NWMiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTI0MC0xNjBxLT" +
            "MzIDAtNTYuNS0yMy41VDE2MC0yNDBxMC0zMyAyMy41LTU2LjVUMjQwLTMyMHEzMyAwIDU2LjUgMjMuNVQzMjAtMjQwcTAgMzMtMj" +
            "MuNSA1Ni41VDI0MC0xNjBabTI0MCAwcS0zMyAwLTU2LjUtMjMuNVQ0MDAtMjQwcTAtMzMgMjMuNS01Ni41VDQ4MC0zMjBxMzMgMC" +
            "A1Ni41IDIzLjVUNTYwLTI0MHEwIDMzLTIzLjUgNTYuNVQ0ODAtMTYwWm0yNDAgMHEtMzMgMC01Ni41LTIzLjVUNjQwLTI0MHEwLT" +
            "MzIDIzLjUtNTYuNVQ3MjAtMzIwcTMzIDAgNTYuNSAyMy41VDgwMC0yNDBxMCAzMy0yMy41IDU2LjVUNzIwLTE2MFpNMjQwLTQwMH" +
            "EtMzMgMC01Ni41LTIzLjVUMTYwLTQ4MHEwLTMzIDIzLjUtNTYuNVQyNDAtNTYwcTMzIDAgNTYuNSAyMy41VDMyMC00ODBxMCAzMy" +
            "0yMy41IDU2LjVUMjQwLTQwMFptMjQwIDBxLTMzIDAtNTYuNS0yMy41VDQwMC00ODBxMC0zMyAyMy41LTU2LjVUNDgwLTU2MHEzMy" +
            "AwIDU2LjUgMjMuNVQ1NjAtNDgwcTAgMzMtMjMuNSA1Ni41VDQ4MC00MDBabTI0MCAwcS0zMyAwLTU2LjUtMjMuNVQ2NDAtNDgwcT" +
            "AtMzMgMjMuNS01Ni41VDcyMC01NjBxMzMgMCA1Ni41IDIzLjVUODAwLTQ4MHEwIDMzLTIzLjUgNTYuNVQ3MjAtNDAwWk0yNDAtNj" +
            "QwcS0zMyAwLTU2LjUtMjMuNVQxNjAtNzIwcTAtMzMgMjMuNS01Ni41VDI0MC04MDBxMzMgMCA1Ni41IDIzLjVUMzIwLTcyMHEwID" +
            "MzLTIzLjUgNTYuNVQyNDAtNjQwWm0yNDAgMHEtMzMgMC01Ni41LTIzLjVUNDAwLTcyMHEwLTMzIDIzLjUtNTYuNVQ0ODAtODAwcT" +
            "MzIDAgNTYuNSAyMy41VDU2MC03MjBxMCAzMy0yMy41IDU2LjVUNDgwLTY0MFptMjQwIDBxLTMzIDAtNTYuNS0yMy41VDY0MC03Mj" +
            "BxMC0zMyAyMy41LTU2LjVUNzIwLTgwMHEzMyAwIDU2LjUgMjMuNVQ4MDAtNzIwcTAgMzMtMjMuNSA1Ni41VDcyMC02NDBaIiBmaW" +
            "xsPSIjYzIyNTVjIi8+PC9zdmc+PC9zdmc+",
        // container -> Material Symbols "archive"
        "container":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwYzg1OTkiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0ibTQ4MC0yNDAgMT" +
            "YwLTE2MC01Ni01Ni02NCA2NHYtMTY4aC04MHYxNjhsLTY0LTY0LTU2IDU2IDE2MCAxNjBaTTIwMC0xMjBxLTMzIDAtNTYuNS0yMy" +
            "41VDEyMC0yMDB2LTQ5OXEwLTE0IDQuNS0yN3QxMy41LTI0bDUwLTYxcTExLTE0IDI3LjUtMjEuNVQyNTAtODQwaDQ2MHExOCAwID" +
            "M0LjUgNy41VDc3Mi04MTFsNTAgNjFxOSAxMSAxMy41IDI0dDQuNSAyN3Y0OTlxMCAzMy0yMy41IDU2LjVUNzYwLTEyMEgyMDBabT" +
            "E2LTYwMGg1MjhsLTM0LTQwSDI1MGwtMzQgNDBaIiBmaWxsPSIjMGM4NTk5Ii8+PC9zdmc+PC9zdmc+",
        // terraform -> Material Symbols "architecture"
        "terraform":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNjMjI1NWMiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0ibTI3MC0xMjAtMT" +
            "AtODggMTE0LTMxNHExNSAxNCAzMi41IDIzLjVUNDQ0LTQ4NEwzMzQtMTgybC02NCA2MlptNDIwIDAtNjQtNjItMTEwLTMwMnEyMC" +
            "01IDM3LjUtMTQuNVQ1ODYtNTIybDExNCAzMTQtMTAgODhaTTQ4MC01MjBxLTUwIDAtODUtMzV0LTM1LTg1cTAtMzkgMjIuNS02OS" +
            "41VDQ0MC03NTJ2LTg4aDgwdjg4cTM1IDEyIDU3LjUgNDIuNVQ2MDAtNjQwcTAgNTAtMzUgODV0LTg1IDM1Wm0wLTgwcTE3IDAgMj" +
            "guNS0xMS41VDUyMC02NDBxMC0xNy0xMS41LTI4LjVUNDgwLTY4MHEtMTcgMC0yOC41IDExLjVUNDQwLTY0MHEwIDE3IDExLjUgMj" +
            "guNVQ0ODAtNjAwWiIgZmlsbD0iI2MyMjU1YyIvPjwvc3ZnPjwvc3ZnPg==",
        // cert -> Material Symbols "policy"
        "cert":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNlMDMxMzEiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC04MHEtMT" +
            "M5LTM1LTIyOS41LTE1OS41VDE2MC01MTZ2LTI0NGwzMjAtMTIwIDMyMCAxMjB2MjQ0cTAgNjMtMTYuNSAxMjIuNVQ3MzYtMjgwTD" +
            "YxOC0zOThxMTEtMTkgMTYuNS0zOS41VDY0MC00ODBxMC02Ni00Ny0xMTN0LTExMy00N3EtNjYgMC0xMTMgNDd0LTQ3IDExM3EwID" +
            "Y2IDQ3IDExM3QxMTMgNDdxMjEgMCA0MS41LTUuNVQ1NjAtMzQybDEyOSAxMjhxLTQyIDQ5LTk0LjUgODRUNDgwLTgwWm0wLTMyMH" +
            "EtMzMgMC01Ni41LTIzLjVUNDAwLTQ4MHEwLTMzIDIzLjUtNTYuNVQ0ODAtNTYwcTMzIDAgNTYuNSAyMy41VDU2MC00ODBxMCAzMy" +
            "0yMy41IDU2LjVUNDgwLTQwMFoiIGZpbGw9IiNlMDMxMzEiLz48L3N2Zz48L3N2Zz4=",
        // auth -> Material Symbols "verified_user"
        "auth":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNlMDMxMzEiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0ibTQzOC0zMzggMj" +
            "I2LTIyNi01Ny01Ny0xNjkgMTY5LTg0LTg0LTU3IDU3IDE0MSAxNDFabTQyIDI1OHEtMTM5LTM1LTIyOS41LTE1OS41VDE2MC01MT" +
            "Z2LTI0NGwzMjAtMTIwIDMyMCAxMjB2MjQ0cTAgMTUyLTkwLjUgMjc2LjVUNDgwLTgwWiIgZmlsbD0iI2UwMzEzMSIvPjwvc3ZnPj" +
            "wvc3ZnPg==",
        // waf -> Material Symbols "shield"
        "waf":
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NiIgaGVpZ2" +
            "h0PSI1NiIgdmlld0JveD0iMCAwIDU2IDU2Ij48cmVjdCB4PSIxLjAiIHk9IjEuMCIgd2lkdGg9IjU0LjAiIGhlaWdodD0iNTQuMC" +
            "Igcng9IjEyIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiNlMDMxMzEiIHN0cm9rZS13aWR0aD0iMiIvPjxzdmcgeD0iMTEuMCIgeT" +
            "0iMTEuMCIgd2lkdGg9IjM0IiBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIC05NjAgOTYwIDk2MCI+PHBhdGggZD0iTTQ4MC04MHEtMT" +
            "M5LTM1LTIyOS41LTE1OS41VDE2MC01MTZ2LTI0NGwzMjAtMTIwIDMyMCAxMjB2MjQ0cTAgMTUyLTkwLjUgMjc2LjVUNDgwLTgwWi" +
            "IgZmlsbD0iI2UwMzEzMSIvPjwvc3ZnPjwvc3ZnPg==",
    ]

    /// The Material Symbol behind each component, so a self-test can assert the
    /// mapping is complete and one-to-one without re-deriving it from base64.
    static let symbolNames: [String: String] = [
        "server": "dns",
        "k8s": "deployed_code",
        "db": "database",
        "queue": "list_alt",
        "lb": "device_hub",
        "secrets": "lock",
        "actor": "person",
        "ec2": "computer",
        "lambda": "bolt",
        "ecs": "grid_view",
        "eks": "hub",
        "alb": "alt_route",
        "apigw": "login",
        "cloudfront": "public",
        "route53": "travel_explore",
        "s3": "inventory_2",
        "rds": "storage",
        "dynamodb": "table_chart",
        "elasticache": "speed",
        "sqs": "forum",
        "sns": "campaign",
        "eventbridge": "shuffle",
        "kinesis": "waves",
        "stepfunctions": "account_tree",
        "iam": "badge",
        "secretsmanager": "key",
        "cloudwatch": "visibility",
        "vpc": "account_balance",
        "deploy": "rocket_launch",
        "k8ssvc": "share",
        "ingress": "route",
        "configmap": "description",
        "namespace": "folder_managed",
        "statefulset": "layers",
        "cronjob": "schedule",
        "node": "developer_board",
        "cdn": "cell_tower",
        "dns": "language",
        "firewall": "security",
        "proxy": "swap_calls",
        "vpn": "vpn_lock",
        "internet": "cloud",
        "subnet": "map",
        "cache": "memory",
        "blob": "folder",
        "warehouse": "warehouse",
        "search": "search",
        "stream": "sync_alt",
        "metrics": "monitoring",
        "logs": "receipt_long",
        "traces": "timeline",
        "dashboard": "dashboard",
        "alert": "warning",
        "oncall": "call",
        "repo": "book",
        "pipeline": "build",
        "registry": "apps",
        "container": "archive",
        "terraform": "architecture",
        "cert": "policy",
        "auth": "verified_user",
        "waf": "shield",
    ]

    /// The glyph hue each component is drawn in, mirroring
    /// `DiagramComponentRole.strokeColor`. Asserted equal in the self-test.
    static let glyphHexes: [String: String] = [
        "server": "#1971c2",
        "k8s": "#0c8599",
        "db": "#2f9e44",
        "queue": "#f08c00",
        "lb": "#9c36b5",
        "secrets": "#e03131",
        "actor": "#1e1e1e",
        "ec2": "#1971c2",
        "lambda": "#1971c2",
        "ecs": "#0c8599",
        "eks": "#0c8599",
        "alb": "#9c36b5",
        "apigw": "#9c36b5",
        "cloudfront": "#9c36b5",
        "route53": "#9c36b5",
        "s3": "#2f9e44",
        "rds": "#2f9e44",
        "dynamodb": "#2f9e44",
        "elasticache": "#2f9e44",
        "sqs": "#f08c00",
        "sns": "#f08c00",
        "eventbridge": "#f08c00",
        "kinesis": "#f08c00",
        "stepfunctions": "#f08c00",
        "iam": "#e03131",
        "secretsmanager": "#e03131",
        "cloudwatch": "#0ca678",
        "vpc": "#343a40",
        "deploy": "#0c8599",
        "k8ssvc": "#9c36b5",
        "ingress": "#9c36b5",
        "configmap": "#2f9e44",
        "namespace": "#343a40",
        "statefulset": "#0c8599",
        "cronjob": "#0c8599",
        "node": "#1971c2",
        "cdn": "#9c36b5",
        "dns": "#9c36b5",
        "firewall": "#e03131",
        "proxy": "#9c36b5",
        "vpn": "#e03131",
        "internet": "#343a40",
        "subnet": "#343a40",
        "cache": "#2f9e44",
        "blob": "#2f9e44",
        "warehouse": "#2f9e44",
        "search": "#2f9e44",
        "stream": "#f08c00",
        "metrics": "#0ca678",
        "logs": "#0ca678",
        "traces": "#0ca678",
        "dashboard": "#0ca678",
        "alert": "#0ca678",
        "oncall": "#0ca678",
        "repo": "#c2255c",
        "pipeline": "#c2255c",
        "registry": "#c2255c",
        "container": "#0c8599",
        "terraform": "#c2255c",
        "cert": "#e03131",
        "auth": "#e03131",
        "waf": "#e03131",
    ]
}
